name: Deploy AWS CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codice
        uses: actions/checkout@v3

      - name: Installa AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Deploy Backend su AWS Lambda
        run: |
          zip -r backend.zip backend
          aws lambda update-function-code --function-name AWSFriendlyCounsellorLambda --zip-file fileb://backend.zip
