import { api } from './api.js';
import { beginLogin, handleCallback, isSignedIn, logout } from './auth.js';
import { loadSettings, saveSettings, resetSettings, setTenantId } from './config.js';
import { $, currentRoute, queryParams, routeTo, toast, esc, download, encodeHtmlReport } from './utils.js';
import { zipFiles } from './zip.js';
import { parseCostFile } from './cur-parser.js';
import { recordDiagnostic, diagnosticSnapshot, clearDiagnostics } from './diagnostics.js';
import * as V from './views.js';

const app=$('#app');
const state={settings:loadSettings(),identity:null,health:null,healthCheckedAt:0,tenant:null,projects:[],projectsHasMore:false,analyses:[],members:[],audit:[],project:null,workspace:null,gamification:null,pricingStatus:null,storageInfo:null,backupStatus:null,recovery:[],estimates:[],actuals:[],lastRequest:null,lastAnalysis:null,lastIac:null,lastReport:null,discovery:null,installPrompt:null};
const templates={
  SaaS:'A multi-tenant SaaS web application with customer login, account administration, REST APIs, file uploads, background jobs, notifications and an analytics dashboard.',
  'E-commerce':'An e-commerce storefront with customer accounts, product browsing, checkout integration, order processing, images, transactional notifications and operational analytics.',
  API:'A public REST API used by web and mobile clients with authentication, tenant-scoped data, asynchronous jobs, webhook processing, monitoring and rate protection.',
  Data:'A data platform that ingests files and events, validates and transforms data, stores durable history and exposes analytics to an internal dashboard.',
  ML:'A web application that accepts user input, runs machine-learning inference asynchronously, stores results, exposes history and requires observability and access control.'
};

function formObject(form){const fd=new FormData(form),o=Object.fromEntries(fd.entries());for(const c of form.querySelectorAll('input[type=checkbox]'))o[c.name]=c.checked;return o}
function analysisRequest(o){return {description:String(o.description||'').trim(),estimated_users:Number(o.estimated_users),budget:o.budget,region:o.region,advanced_guide:o.advanced_guide!==false&&o.advanced_guide!=='false'}}
function projectPayload(o){return {name:String(o.name||'').trim(),description:String(o.description||'').trim(),estimated_users:Number(o.estimated_users),budget:o.budget,region:o.region,status:o.status||'draft'}}
function showBusy(button,label='Working…'){if(!button)return()=>{};const old=button.innerHTML;button.disabled=true;button.innerHTML=`<span class="spinner"></span>${label}`;return()=>{button.disabled=false;button.innerHTML=old}}
function handleError(e,context='Request failed'){console.error(e);recordDiagnostic('error',e?.message||String(e),{context,status:e?.status||null,route:currentRoute()});toast(`${context}: ${e.message}`, 'error');}

async function bootstrapCommon({force=false}={}){state.settings=loadSettings();const now=Date.now();if(force||!state.health||now-state.healthCheckedAt>30000){try{state.health=await api.health()}catch{state.health=null}state.healthCheckedAt=now}if(isSignedIn()){if(force||!state.identity){try{state.identity=await api.me()}catch(e){if(state.settings.authMode==='cognito'&&e.status===401)state.identity=null}}if(state.settings.tenantId){if(force||!state.tenant||state.tenant.id!==state.settings.tenantId){try{state.tenant=(await api.getTenant(state.settings.tenantId)).tenant}catch{state.tenant=null}}}else state.tenant=null}}
async function loadProjects({limit=25,cursor=null}={}){if(!state.settings.tenantId){state.projects=[];state.projectsHasMore=false;return {projects:[],next_cursor:null}}try{const page=await api.listProjects({limit,cursor});state.projects=page.projects;state.projectsHasMore=!!page.next_cursor;return page}catch(e){state.projects=[];state.projectsHasMore=false;throw e}}
async function loadLatest(){let latest=null;for(const p of state.projects.slice(0,5)){try{const x=(await api.listProjectAnalyses(p.id,{limit:1})).analysis_versions[0];if(x&&(!latest||new Date(x.created_at)>new Date(latest.created_at)))latest=x}catch{}}return latest}
async function collectPages(fetchPage,key,{limit=100,max=500}={}){const all=[];let cursor=null;do{const page=await fetchPage({limit,cursor});all.push(...(page[key]||[]));cursor=page.next_cursor||null}while(cursor&&all.length<max);return {items:all.slice(0,max),truncated:!!cursor}}

async function render(){state.settings=loadSettings();const route=currentRoute();if(route==='/'||route==='/login'){app.innerHTML=V.landing(state.settings);return}if(route==='/settings'){app.innerHTML=V.shell({route,settings:state.settings,identity:state.identity,health:state.health,body:V.settingsPage(state.settings)});return}if(route==='/about'){app.innerHTML=V.shell({route,settings:state.settings,identity:state.identity,health:state.health,body:V.aboutPage(state.settings)});return}if(route==='/data'){try{await bootstrapCommon()}catch{}state.storageInfo=await api.storageInfo().catch(()=>({storage:'remote backend',network_required:true}));state.backupStatus=await api.backupStatus().catch(()=>({recommended:false,critical:false}));state.recovery=(await api.recoveryList().catch(()=>({checkpoints:[]}))).checkpoints||[];app.innerHTML=V.shell({route,settings:state.settings,identity:state.identity,health:state.health,body:V.dataPage(state.settings,state.storageInfo,state.backupStatus,state.recovery)});return}if(state.settings.authMode==='cognito'&&!isSignedIn()){app.innerHTML=V.landing(state.settings);toast('Sign in to open the application.','info');return}try{await bootstrapCommon()}catch(e){handleError(e,'Connection')}if(!state.settings.tenantId||!state.tenant){app.innerHTML=V.shell({route,settings:state.settings,identity:state.identity,health:state.health,body:V.onboarding(state.settings)});return}
  let body='';
  try{
    if(route==='/dashboard'){await loadProjects({limit:5});try{state.gamification=await api.gamification(state.settings.tenantId)}catch{state.gamification=null}state.backupStatus=await api.backupStatus().catch(()=>null);state.storageInfo=await api.storageInfo().catch(()=>null);state.pricingStatus=await api.pricingStatus().catch(()=>null);body=V.dashboard({tenant:state.tenant,projects:state.projects,projectsHasMore:state.projectsHasMore,health:state.health,identity:state.identity,latest:await loadLatest(),gamification:state.gamification,backupStatus:state.backupStatus,storageInfo:state.storageInfo,pricingStatus:state.pricingStatus})}
    else if(route==='/advisor')body=V.advisor(state.lastRequest||{});
    else if(route==='/discovery'){state.discovery=await api.awsDiscoveryGet();body=V.discoveryPage(state.discovery,state.settings)}
    else if(route==='/projects'){const q=queryParams();const page=await loadProjects({limit:50,cursor:q.get('cursor')});body=V.projectsPage(page.projects,page.next_cursor)}
    else if(route.startsWith('/project/')){const id=decodeURIComponent(route.slice('/project/'.length));state.project=(await api.getProject(id)).project;const q=queryParams();const page=await api.listProjectAnalyses(id,{limit:50,cursor:q.get('analysis_cursor')});state.analyses=page.analysis_versions;body=V.projectDetail(state.project,state.analyses,page.next_cursor)}
    else if(route==='/team'){const q=queryParams();const page=await api.listMemberships(state.settings.tenantId,{limit:50,cursor:q.get('cursor')});state.members=page.memberships;body=V.teamPage(state.members,page.next_cursor,state.settings)}
    else if(route==='/audit'){const q=queryParams();const page=await api.listAudit(state.settings.tenantId,{limit:50,cursor:q.get('cursor')});state.audit=page.audit_events;body=V.auditPage(state.audit,page.next_cursor,state.settings)}
    else if(route==='/finops'){const q=queryParams();const pp=await collectPages(page=>api.listProjects(page),'projects');state.projects=pp.items;state.pricingStatus=await api.pricingStatus().catch(()=>null);const pid=q.get('project');let selected=null,analyses=[],estimates=[],actuals=[],workspace=null;if(pid){selected=(await api.getProject(pid)).project;const av=await collectPages(page=>api.listProjectAnalyses(pid,page),'analysis_versions');analyses=av.items;const selectedVersion=Number(q.get('version')||analyses[0]?.version||0);if(selectedVersion)workspace=(await api.getWorkspace(pid,selectedVersion)).workspace;const ep=await collectPages(page=>api.listAccountEstimates(pid,page),'estimates');estimates=ep.items;const ap=await collectPages(page=>api.listActualCosts(pid,page),'snapshots');actuals=ap.items;state.project=selected;state.workspace=workspace;state.analyses=analyses;state.estimates=estimates;state.actuals=actuals}body=V.finopsPage({projects:state.projects,selectedProject:selected,analyses,workspace,pricingStatus:state.pricingStatus,estimates,actuals,settings:state.settings})}
    else if(route==='/privacy'){body=V.privacyPage(state.settings)}
    else {body=V.errorCard('Page not found',route)}
  }catch(e){body=V.errorCard('Unable to load this page',e.message)}
  app.innerHTML=V.shell({route,settings:state.settings,identity:state.identity,health:state.health,body});
}

function terraformOutput(iac){state.lastIac=iac;const t=iac.terraform;return `<section class="panel generated"><div class="panel-head"><div><div class="eyebrow">Infrastructure as code</div><h2>Terraform baseline</h2></div><span class="pill ${t.status==='baseline_ready'?'active':'info'}">${esc(t.status)}</span></div><p class="muted">${t.supported_services.length} supported service mappings · ${t.deferred_services.length} deferred.</p><div class="file-tabs">${Object.entries(t.files).map(([n,c],i)=>`<details ${i===0?'open':''}><summary>${esc(n)} <span>${c.split('\n').length} lines</span></summary><pre><code>${esc(c)}</code></pre></details>`).join('')}</div><div class="form-actions"><button class="btn primary" data-action="download-terraform">Download Terraform ZIP</button><button class="btn ghost" data-action="copy-main-tf">Copy main.tf</button></div><ol class="compact">${t.instructions.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></section>`}
function reportOutput(report){state.lastReport=report;const safeDoc=`<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:system-ui;padding:32px;line-height:1.55;color:#172033}table{border-collapse:collapse;width:100%}th,td{border:1px solid #ddd;padding:8px;text-align:left}h1,h2,h3{color:#0b203d}</style></head><body>${report.narrative_html}</body></html>`;return `<section class="panel generated"><div class="panel-head"><div><div class="eyebrow">Human-readable report</div><h2>Architecture report</h2></div><div><button class="btn mini" data-action="download-report">Download HTML</button> <button class="btn mini ghost" data-action="print-report">Print / PDF</button></div></div><iframe class="report-frame" sandbox="allow-modals" title="Architecture report" srcdoc="${esc(safeDoc)}"></iframe></section>`}
async function generateIac(req,target='#generated-output'){const out=$(target);if(out)out.innerHTML='<div class="loading-card"><span class="spinner"></span> Generating Terraform…</div>';try{const r=await api.iac(req);if(out)out.innerHTML=terraformOutput(r)}catch(e){if(out)out.innerHTML=V.errorCard('Terraform generation failed',e.message)}}
async function generateReport(req,target='#generated-output'){const out=$(target);if(out)out.innerHTML='<div class="loading-card"><span class="spinner"></span> Generating report…</div>';try{const r=await api.narrative(req);if(out)out.innerHTML=reportOutput(r)}catch(e){if(out)out.innerHTML=V.errorCard('Report generation failed',e.message)}}
function requestFromProject(p){return {description:p.description,estimated_users:p.estimated_users,budget:p.budget,region:p.region,advanced_guide:true}}

app.addEventListener('submit',async e=>{
  const f=e.target;if(!(f instanceof HTMLFormElement))return;e.preventDefault();
  if(f.id==='settings-form'){const o=formObject(f);state.settings=saveSettings(o);state.identity=null;state.tenant=null;state.health=null;toast('Settings saved','success');await bootstrapCommon({force:true});await render();return}
  if(f.id==='create-tenant-form'){const done=showBusy(f.querySelector('button[type=submit]'),'Creating…');try{const o=formObject(f);const payload={name:String(o.name||'').trim()};const slug=String(o.slug||'').trim();if(slug)payload.slug=slug;const r=await api.createTenant(payload);setTenantId(r.tenant.id);state.tenant=r.tenant;toast('Workspace created','success');routeTo('/dashboard')}catch(x){handleError(x,'Create workspace')}finally{done()}return}
  if(f.id==='connect-tenant-form'){const id=formObject(f).tenantId.trim();setTenantId(id);try{await bootstrapCommon();if(!state.tenant)throw new Error('Tenant not found or not accessible');toast('Workspace connected','success');routeTo('/dashboard')}catch(x){setTenantId('');handleError(x,'Connect workspace')}return}
  if(f.id==='advisor-form'){const b=f.querySelector('button[type=submit]'),done=showBusy(b,'Analyzing…');try{state.lastRequest=analysisRequest(formObject(f));state.lastAnalysis=await api.analyze(state.lastRequest);$('#advisor-result').innerHTML=V.analysisResult(state.lastAnalysis);$('#advisor-result').scrollIntoView({behavior:'smooth',block:'start'});toast('Analysis ready','success')}catch(x){handleError(x,'Analysis')}finally{done()}return}
  if(f.id==='project-create-form'){const done=showBusy(f.querySelector('button[type=submit]'),'Creating…');try{const r=await api.createProject(projectPayload(formObject(f)));toast('Project created','success');routeTo(`/project/${r.project.id}`)}catch(x){handleError(x,'Create project')}finally{done()}return}
  if(f.id==='project-edit-form'){const o=formObject(f),p={expected_revision:Number(o.expected_revision),name:o.name.trim(),description:o.description.trim(),estimated_users:Number(o.estimated_users),budget:o.budget,region:o.region,status:o.status};const done=showBusy(f.querySelector('button[type=submit]'),'Saving…');try{await api.updateProject(state.project.id,p);toast('Project updated','success');await render()}catch(x){handleError(x,'Update project')}finally{done()}return}
  if(f.id==='account-estimate-form'){const o=formObject(f),done=showBusy(f.querySelector('button[type=submit]'),'Creating…');try{await api.createAccountEstimate(state.project.id,Number(o.version),{account_id:o.account_id,rate_type:o.rate_type,ttl_days:Number(o.ttl_days)});toast(state.settings.authMode==='standalone'?'Local planning estimate persisted':'Account-aware estimate persisted','success');await render()}catch(x){handleError(x,state.settings.authMode==='standalone'?'Local planning estimate':'Pricing Calculator estimate')}finally{done()}return}
  if(f.id==='actual-cost-form'){const o=formObject(f),done=showBusy(f.querySelector('button[type=submit]'),'Collecting…');try{await api.createActualCost(state.project.id,{estimate_id:o.estimate_id,account_id:o.account_id,start_date:o.start_date,end_date:o.end_date,metric:o.metric,actual_total:o.actual_total===''?undefined:Number(o.actual_total)});toast(state.settings.authMode==='standalone'?'Manual actual-cost snapshot persisted':'Cost Explorer snapshot persisted','success');await render()}catch(x){handleError(x,state.settings.authMode==='standalone'?'Manual actual cost':'Cost Explorer snapshot')}finally{done()}return}
  if(f.id==='cur-import-form'){const o=formObject(f),file=f.querySelector('input[name=cur_file]')?.files?.[0],done=showBusy(f.querySelector('button[type=submit]'),'Importing…');try{let rows,import_stats=null;if(file){const progress=$('#cur-progress');const parsed=await parseCostFile(file,{fallbackDate:o.start_date,onProgress:p=>{if(progress)progress.textContent=p.total?`Reading ${Math.min(100,Math.round((p.bytes||0)/p.total*100))}%…`:'Reading…'}});rows=parsed.rows;import_stats={...parsed.stats,file_name:file.name,file_size:file.size};if(progress)progress.textContent=`${parsed.stats.accepted_rows} valid rows → ${parsed.stats.aggregated_rows} aggregates`;}else{try{rows=JSON.parse(o.rows)}catch{throw new Error('Choose a CSV/NDJSON/JSON file or paste valid JSON rows.')}if(!Array.isArray(rows)||!rows.length)throw new Error('CUR rows must be a non-empty JSON array');import_stats={input_rows:rows.length,accepted_rows:rows.length,rejected_rows:0,aggregated_rows:rows.length,source:'pasted-json'}}await api.importCur2(state.project.id,{estimate_id:o.estimate_id,account_id:o.account_id,start_date:o.start_date,end_date:o.end_date,rows,import_stats});toast(`Actual-cost import persisted · ${rows.length} aggregate rows`,'success');await render()}catch(x){handleError(x,'CUR / actual-cost import')}finally{done()}return}
  if(f.id==='usage-pricing-form'){const o=formObject(f),done=showBusy(f.querySelector('button[type=submit]'),'Pricing…');try{const usage=JSON.parse(o.usage_json);const transfer_paths=JSON.parse(o.transfer_paths_json||'[]');const service_ids=String(o.service_ids||'').split(',').map(x=>x.trim()).filter(Boolean);const r=await api.pricingQuote({region:o.region,usage,service_ids,transfer_paths,strict_authoritative:o.strict_authoritative===true});$('#pricing-preview').innerHTML=V.pricingPreview(r);toast('Explicit-usage quote ready','success')}catch(x){handleError(x,'Explicit usage pricing')}finally{done()}return}
  if(f.id==='region-simulation-form'){const o=formObject(f),done=showBusy(f.querySelector('button[type=submit]'),'Comparing…');try{const usage=JSON.parse(o.usage_json);const service_ids=String(o.service_ids||'').split(',').map(x=>x.trim()).filter(Boolean);const regions=String(o.regions||'').split(',').map(x=>x.trim()).filter(Boolean);const r=await api.simulateRegions({usage,service_ids,regions});$('#region-preview').innerHTML=V.regionComparison(r);toast('Region simulation ready','success')}catch(x){handleError(x,'Region simulation')}finally{done()}return}
  if(f.id==='pricing-catalog-import-form'){const input=f.querySelector('input[type=file]'),file=input?.files?.[0];if(!file){toast('Choose a pricing snapshot JSON file first','error');return}const done=showBusy(f.querySelector('button[type=submit]'),'Importing…');try{const r=await api.importPricingCatalog(await file.text());toast(`Pricing snapshot ${r.catalog.version} imported`,'success');await render()}catch(x){handleError(x,'Pricing snapshot import')}finally{done()}return}
  if(f.id==='backup-import-form'){const input=f.querySelector('input[type=file]'),file=input?.files?.[0];if(!file){toast('Choose an AWSFC backup JSON file first','error');return}const o=formObject(f),done=showBusy(f.querySelector('button[type=submit]'),'Verifying…');try{const text=await file.text();const r=await api.backupImport(text,String(o.passphrase||''));if(r.tenant_id)setTenantId(r.tenant_id);state.identity=null;state.tenant=null;state.health=null;toast(`Backup verified and restored · ${r.projects} projects`,'success');routeTo('/dashboard')}catch(x){handleError(x,'Restore backup')}finally{done()}return}
  if(f.id==='discovery-import-form'){const input=f.querySelector('input[type=file]'),file=input?.files?.[0];if(!file){toast('Choose an AWS discovery JSON file first','error');return}if(file.size>25*1024*1024){toast('Discovery bundle exceeds the 25 MB browser import limit','error');return}const done=showBusy(f.querySelector('button[type=submit]'),'Validating…');try{const payload=JSON.parse(await file.text());const r=await api.awsDiscoveryImport(payload);state.discovery=r;toast(`AWS inventory imported · ${r.summary.resource_count} resources`,'success');await render()}catch(x){handleError(x,'AWS discovery import')}finally{done()}return}
  if(f.id==='member-create-form'){const o=formObject(f),done=showBusy(f.querySelector('button[type=submit]'),'Granting…');try{await api.createMembership(state.settings.tenantId,{subject:o.subject.trim(),role:o.role});toast('Membership created','success');await render()}catch(x){handleError(x,'Create membership')}finally{done()}return}
  if(f.id==='member-edit-form'){const o=formObject(f),done=showBusy(f.querySelector('button[type=submit]'),'Updating…');try{await api.updateMembership(state.settings.tenantId,o.subject,{expected_revision:Number(o.expected_revision),role:o.role,status:o.status});toast('Membership updated','success');await render()}catch(x){handleError(x,'Update membership')}finally{done()}return}
});

app.addEventListener('click',async e=>{const el=e.target.closest('[data-action],[data-template]');if(!el)return;
  if(el.dataset.template){const ta=$('#advisor-form textarea[name=description]');if(ta)ta.value=templates[el.dataset.template]||'';return}
  const a=el.dataset.action;
  if(a==='login'){try{await beginLogin()}catch(x){handleError(x,'Sign in')}}
  else if(a==='logout')logout();
  else if(a==='toggle-menu')document.body.classList.toggle('menu-open');
  else if(a==='show-project-form')$('#project-create-slot').innerHTML=V.projectCreateForm();
  else if(a==='hide-project-form')$('#project-create-slot').innerHTML='';
  else if(a==='save-analysis-project'){if(!state.lastRequest)return;const name=prompt('Project name','New advised project');if(!name)return;try{const r=await api.createProject({name,description:state.lastRequest.description,estimated_users:state.lastRequest.estimated_users,budget:state.lastRequest.budget,region:state.lastRequest.region,status:'active'});await api.createProjectAnalysis(r.project.id,{advanced_guide:state.lastRequest.advanced_guide});toast('Project and first immutable analysis saved','success');routeTo(`/project/${r.project.id}`)}catch(x){handleError(x,'Save project')}}
  else if(a==='generate-iac'){if(state.lastRequest)await generateIac(state.lastRequest)}
  else if(a==='generate-report'){if(state.lastRequest)await generateReport(state.lastRequest)}
  else if(a==='run-project-analysis'){const done=showBusy(el,'Running…');try{const r=await api.createProjectAnalysis(state.project.id,{advanced_guide:true});state.lastAnalysis=r.analysis_version.result;toast(`Analysis v${r.analysis_version.version} persisted`,'success');await render();setTimeout(()=>{const slot=$('#analysis-version-slot');if(slot)slot.innerHTML=V.analysisResult(state.lastAnalysis,{showPersist:false})},20)}catch(x){handleError(x,'Persist analysis')}finally{done()}}
  else if(a==='project-iac')await generateIac(requestFromProject(state.project),'#project-output');
  else if(a==='project-report')await generateReport(requestFromProject(state.project),'#project-output');
  else if(a==='open-analysis'){try{const r=await api.getProjectAnalysis(state.project.id,Number(el.dataset.version));$('#analysis-version-slot').innerHTML=V.analysisResult(r.analysis_version.result,{showPersist:false});$('#analysis-version-slot').scrollIntoView({behavior:'smooth'})}catch(x){handleError(x,'Open analysis')}}
  else if(a==='edit-member'){$('#member-edit-slot').innerHTML=V.memberEditForm({subject:el.dataset.subject,role:el.dataset.role,status:el.dataset.status,revision:Number(el.dataset.revision)});$('#member-edit-slot').scrollIntoView({behavior:'smooth'})}
  else if(a==='download-terraform'&&state.lastIac){download('aws-friendly-counsellor-terraform.zip',zipFiles(state.lastIac.terraform.files),'application/zip')}
  else if(a==='copy-main-tf'&&state.lastIac){navigator.clipboard?.writeText(state.lastIac.terraform.files['main.tf']||'').then(()=>toast('main.tf copied','success'))}
  else if(a==='download-report'&&state.lastReport){download('aws-friendly-counsellor-report.html',encodeHtmlReport('AWS Friendly Counsellor report',state.lastReport.narrative_html),'text/html;charset=utf-8')}
  else if(a==='print-report'){const fr=$('.report-frame');if(fr?.contentWindow)fr.contentWindow.print()}
  else if(a==='compare-regions'){if(state.lastAnalysis?.usage_profile){const out=$('#generated-output');if(out)out.innerHTML='<div class="loading-card"><span class="spinner"></span> Comparing regions…</div>';try{const r=await api.simulateRegions({usage:state.lastAnalysis.usage_profile,service_ids:(state.lastAnalysis.services||[]).map(x=>x.id),regions:['us-east-1','eu-west-1','eu-central-1','ap-southeast-1']});if(out)out.innerHTML=V.regionComparison(r)}catch(x){if(out)out.innerHTML=V.errorCard('Region simulation failed',x.message)}}}
  else if(a==='preview-public-pricing'){const version=Number($('#finops-version')?.value);if(!state.project||!version)return;const out=$('#pricing-preview');if(out)out.innerHTML='<div class="loading-card"><span class="spinner"></span> Pricing explicit usage…</div>';try{const w=await api.getWorkspace(state.project.id,version);const result=w.workspace.result_payload||w.workspace.result||{};const q=await api.pricingQuote({region:state.project.region,usage:result.usage_profile,service_ids:(result.services||[]).map(x=>x.id),transfer_paths:[]});if(out)out.innerHTML=V.pricingPreview(q)}catch(x){if(out)out.innerHTML=V.errorCard('Pricing preview failed',x.message)}}
  else if(a==='export-report-bundle'){if(!state.project)return;const version=Number($('#report-bundle-version')?.value||el.dataset.version);if(!version)return;try{const r=await api.getReportBundle(state.project.id,version);download(`awsfc-${state.project.id}-v${version}-report.zip`,zipFiles(r.files),'application/zip');toast(`Report bundle exported · SHA ${r.workspace_sha256.slice(0,12)}…`,'success')}catch(x){handleError(x,'Report bundle')}}
  else if(a==='estimate-refresh'){try{await api.refreshAccountEstimate(state.project.id,el.dataset.id);toast('Estimate refreshed','success');await render()}catch(x){handleError(x,'Refresh estimate')}}
  else if(a==='estimate-extend'){const rev=Number(el.dataset.revision),days=Number(prompt('Extend estimate by how many days?','30'));if(!days)return;try{await api.extendAccountEstimate(state.project.id,el.dataset.id,{expected_revision:rev,ttl_days:days});toast('Estimate expiry extended','success');await render()}catch(x){handleError(x,'Extend estimate')}}
  else if(a==='estimate-revisions'){try{const r=await api.listAccountEstimateRevisions(state.project.id,el.dataset.id);$('#finops-output').innerHTML=V.revisionPanel('Pricing estimate revisions',r.revisions)}catch(x){handleError(x,'Estimate revisions')}}
  else if(a==='actual-refresh'){try{await api.refreshActualCost(state.project.id,el.dataset.id);toast(state.settings.authMode==='standalone'?'Manual actual-cost snapshot refreshed':'Cost Explorer snapshot refreshed','success');await render()}catch(x){handleError(x,state.settings.authMode==='standalone'?'Refresh manual actual cost':'Refresh Cost Explorer snapshot')}}
  else if(a==='actual-revisions'){try{const r=await api.listActualCostRevisions(state.project.id,el.dataset.id);$('#finops-output').innerHTML=V.revisionPanel('Actual-cost revisions',r.revisions)}catch(x){handleError(x,'Actual-cost revisions')}}
  else if(a==='privacy-export'){try{const data=await api.privacyExport();download('awsfc-my-data.json',JSON.stringify(data,null,2)+'\n','application/json;charset=utf-8');toast('Privacy export downloaded','success')}catch(x){handleError(x,'Privacy export')}}
  else if(a==='privacy-delete'){if(!confirm(state.settings.authMode==='standalone'?'Prepare local erasure? This can delete the entire browser vault after a second confirmation.':'Begin the erasure workflow for your active tenant membership?'))return;try{const r=await api.privacyDelete();const out=$('#privacy-output');if(out)out.innerHTML=`<div class="panel generated"><strong>${esc(r.deletion_request.status)}</strong><p>${esc(r.deletion_request.note)}</p><small>${esc(r.deletion_request.request_id)}</small></div>`;if(state.settings.authMode==='standalone'&&confirm('Final confirmation: permanently delete the local AWS Friendly Counsellor vault from this browser? Exported backup files will NOT be deleted.')){await api.resetLocalData();setTenantId('');state.identity=null;state.tenant=null;state.health=null;toast('Local data erased','success');routeTo('/')}else toast('Erasure workflow recorded','success')}catch(x){handleError(x,'Erasure request')}}
  else if(a==='backup-export'){try{const payload=await api.backupExport();download(`awsfc-local-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(payload,null,2)+'\n','application/json;charset=utf-8');toast('Integrity-checked backup downloaded','success');if(currentRoute()==='/data')await render()}catch(x){handleError(x,'Backup export')}}
  else if(a==='backup-export-encrypted'){const pass=prompt('Choose a passphrase (minimum 8 characters). It cannot be recovered by the app.');if(pass===null)return;const confirmPass=prompt('Re-enter the backup passphrase to prevent an unrecoverable typo.');if(confirmPass===null)return;if(pass!==confirmPass){toast('Passphrases do not match; encrypted backup was not created','error');return}try{const payload=await api.backupExportEncrypted(pass);download(`awsfc-encrypted-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(payload,null,2)+'\n','application/json;charset=utf-8');toast('AES-GCM encrypted backup downloaded','success');if(currentRoute()==='/data')await render()}catch(x){handleError(x,'Encrypted backup')}}
  else if(a==='request-persistence'){try{const r=await api.requestPersistentStorage();toast(r.persisted?'Persistent storage granted':'Browser kept best-effort storage; keep external backups',r.persisted?'success':'info');await render()}catch(x){handleError(x,'Storage persistence')}}
  else if(a==='recovery-restore'){if(!confirm('Restore this local recovery checkpoint? The current state will itself be checkpointed first.'))return;try{const r=await api.recoveryRestore(el.dataset.id);if(r.tenant_id)setTenantId(r.tenant_id);state.identity=null;state.tenant=null;state.health=null;toast(`Recovery checkpoint restored · ${r.projects} projects`,'success');routeTo('/dashboard')}catch(x){handleError(x,'Recovery restore')}}
  else if(a==='discovery-export'){try{const r=state.discovery?.discovery?state.discovery:await api.awsDiscoveryGet();if(!r?.discovery)throw new Error('No AWS discovery inventory is loaded.');download(`awsfc-discovery-${r.discovery.account.id}-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(r.discovery,null,2)+'\n','application/json;charset=utf-8');toast('AWS discovery inventory exported','success')}catch(x){handleError(x,'AWS discovery export')}}
  else if(a==='discovery-clear'){if(!confirm('Clear the imported AWS discovery inventory from this workspace?'))return;try{await api.awsDiscoveryClear();state.discovery=null;toast('AWS discovery inventory cleared','success');await render()}catch(x){handleError(x,'AWS discovery clear')}}
  else if(a==='diagnostics-export'){try{const snap=await diagnosticSnapshot({settings:state.settings,health:state.health,storage:await api.storageInfo().catch(()=>null)});download(`awsfc-diagnostics-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(snap,null,2)+'\n','application/json;charset=utf-8');toast('Local diagnostics downloaded','success')}catch(x){handleError(x,'Diagnostics export')}}
  else if(a==='diagnostics-clear'){clearDiagnostics();toast('Local diagnostics cleared','success')}
  else if(a==='pricing-refresh-bundled'){try{const r=await fetch(`./data/pricing-snapshot.json?ts=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const catalog=await r.json();const saved=await api.importPricingCatalog(catalog);toast(`Pricing snapshot ${saved.catalog.version} updated`,'success');await render()}catch(x){handleError(x,'Pricing snapshot update')}}
  else if(a==='install-app'){if(state.installPrompt){state.installPrompt.prompt();await state.installPrompt.userChoice.catch(()=>null);state.installPrompt=null;await render()}else toast('Install prompt is not available in this browser yet','info')}
  else if(a==='standalone-reset'){if(!confirm('Delete all standalone AWS Friendly Counsellor data stored in this browser? Export a backup first if needed.'))return;try{await api.resetLocalData();setTenantId('');state.identity=null;state.tenant=null;state.health=null;toast('Standalone vault reset','success');routeTo('/')}catch(x){handleError(x,'Reset standalone data')}}
  else if(a==='print')window.print();
  else if(a==='test-connection'){try{const h=await api.health();toast(`Runtime ready: ${h.environment} / ${h.version}`,'success')}catch(x){handleError(x,'Connection test')}}
  else if(a==='reset-settings'){if(confirm('Reset browser settings?')){resetSettings();state.settings=loadSettings();state.identity=null;state.tenant=null;state.health=null;toast('Settings reset','success');await render()}}
});

app.addEventListener('change',e=>{if(e.target?.id==='finops-project'){const id=e.target.value;if(id)routeTo(`/finops?project=${encodeURIComponent(id)}`);else routeTo('/finops')}else if(e.target?.id==='finops-version'&&state.project){routeTo(`/finops?project=${encodeURIComponent(state.project.id)}&version=${encodeURIComponent(e.target.value)}`)}});

window.addEventListener('hashchange',()=>{document.body.classList.remove('menu-open');render()});
window.addEventListener('online',()=>toast('Back online','success'));window.addEventListener('offline',()=>toast('Offline: standalone application remains available','info'));
window.addEventListener('error',e=>recordDiagnostic('window-error',e.message,{filename:e.filename,lineno:e.lineno,colno:e.colno}));
window.addEventListener('unhandledrejection',e=>recordDiagnostic('unhandled-rejection',e.reason?.message||String(e.reason||'unknown')));
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;if(currentRoute()==='/dashboard')render()});

(async function init(){try{await handleCallback()}catch(e){handleError(e,'Login callback')}await bootstrapCommon();await render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(e=>recordDiagnostic('service-worker',e.message));})();
