import { uid, nowIso } from './utils.js';
import { analyzeKnowledge, serviceByName, KNOWLEDGE_VERSION } from './knowledge.js';
import {
  loadVault, saveVault, exportVault, importVault, resetVault, vaultInfo,
  exportEncryptedVault, importEncryptedVault, recoveryList, recoveryRestore,
  backupStatus, requestPersistentStorage
} from './vault.js';

const APP_VERSION='3.19.0-m4lf2';
const WEB_VERSION='M4-LF2';
function meta(){return {request_id:uid('local_req'),processing_time_ms:4,timestamp:nowIso(),version:APP_VERSION,contract_version:'1.13.0'}}
function clone(v){return JSON.parse(JSON.stringify(v))}
function money(v){return `$${Number(v||0).toFixed(2)}`}
async function sha256Hex(text){const bytes=new TextEncoder().encode(text),digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function audit(s,action,type,id,metadata={}){s.audit.unshift({id:uid('audit'),tenant_id:s.tenant?.id||'local',actor_subject:'local-owner',action,resource_type:type,resource_id:id,request_id:uid('local_req'),occurred_at:nowIso(),metadata});if(s.audit.length>2000)s.audit=s.audit.slice(0,2000)}
function page(items,{limit=50,cursor=null}={}){const bounded=Math.max(1,Math.min(100,Number(limit)||50));let offset=0;if(cursor){try{offset=Number(atob(cursor));if(!Number.isInteger(offset)||offset<0)offset=0}catch{offset=0}}const values=items.slice(offset,offset+bounded),next=offset+bounded<items.length?btoa(String(offset+bounded)):null;return {values,next_cursor:next}}
function validDateRange(start,end){const a=Date.parse(start),b=Date.parse(end);return Number.isFinite(a)&&Number.isFinite(b)&&a<b}
function ensureProject(s,id){const p=s.projects.find(x=>x.id===id);if(!p)throw Object.assign(new Error('Project not found'),{status:404});return p}
function ensureEstimate(s,id,estimateId){const e=s.accountEstimates[estimateId];if(!e||e.project_id!==id)throw Object.assign(new Error('Estimate not found for this project'),{status:404});return e}

function servicePlanningCost(service,users,budget){const scale=Math.max(1,Math.log10(Number(users||1)+10));const mult={low:.75,medium:1,high:1.45}[budget]||1;return Math.round(Number(service?.base||5)*scale*mult*100)/100}
function baseStandaloneAnalysis(req){
  const k=analyzeKnowledge(req.description),items=k.services.map((svc,i)=>{const c=servicePlanningCost(svc,req.estimated_users,req.budget);return {id:svc.id,name:svc.name,category:svc.category,essential:i<7,typical_monthly:money(c),free_tier:i<6?'May be partially eligible':'Workload-dependent',why_needed:svc.why,use_case_example:svc.use,region:req.region}});
  const vals=Object.fromEntries(items.map(x=>{const v=Number(x.typical_monthly.slice(1));return[x.name,{name:x.name,minimum:+(v*.55).toFixed(2),maximum:+(v*1.8).toFixed(2),display:`${money(v*.55)} – ${money(v*1.8)}`,free_tier:x.free_tier}]}));
  const typical=Object.values(vals).reduce((a,b)=>a+(b.minimum+b.maximum)/2,0),min=Object.values(vals).reduce((a,b)=>a+b.minimum,0),max=Object.values(vals).reduce((a,b)=>a+b.maximum,0);
  return {project_id:uid('local_proj'),analysis:{project_type:k.project_type,confidence:k.confidence,detected_features:k.features,classifier:k.classifier,knowledge_version:k.knowledge_version,ml_primary:k.ml_primary,ml_probabilities:k.ml_probabilities},services:items,architecture_risks:k.risks,well_architected:k.wellArchitected,cost_analysis:{currency:'USD',period:'monthly',region:req.region,summary:{free_tier_viable:req.estimated_users<5000,minimum:money(min),typical:money(typical),maximum:money(max),minimum_value:min,typical_value:typical,maximum_value:max,budget_alignment:req.budget==='low'?'Cost-conscious baseline':'Balanced against requested budget'},breakdown:vals,assumptions:['Standalone planning range is computed locally from an explainable service model.','Traffic, storage, data transfer, service tiers and managed-service usage materially affect actual AWS charges.']},implementation_guide:{format:req.advanced_guide?'advanced':'essential',project_context:{type:k.project_type,estimated_monthly_active_users:req.estimated_users,budget:req.budget,region:req.region,services_count:items.length,complexity:items.length>10?'high':items.length>6?'medium':'low'},introduction:{title:`Implementation plan for ${k.project_type}`,overview:'Start with identity, network/API boundaries and data ownership, then add observability, security controls and recovery evidence.',estimated_effort:items.length>10?'4–8 weeks':items.length>7?'2–5 weeks':'1–3 weeks',estimated_monthly_cost:money(typical)},prerequisites:['AWS account with billing alerts if deploying','Dedicated non-production environment','Domain/TLS plan for public workloads','Source control and CI'],phases:[{name:'Foundation',duration:'1–3 days',steps:['Define environment boundaries','Define identity/secrets model','Enable budgets and logging']},{name:'Application',duration:'3–10 days',steps:['Deploy compute/API path','Create data layer','Add authentication and tenant controls']},{name:'Hardening',duration:'2–7 days',steps:['Enable edge/security controls','Run rollback and restore drills','Review IAM, quotas and cost assumptions']}],acceptance_checks:['Identity and access model is explicit','Tenant/data boundaries are tested','Alarms are actionable','Restore procedure has measured evidence'],operations:req.advanced_guide?{security:['Use least-privilege IAM','Require MFA for privileged identities','Classify data and define key/secret ownership'],reliability:['Measure recovery time','Test failure paths','Record dependency quotas'],cost_control:['Enable budgets/anomaly detection','Review cost by service','Tune retention and capacity']}:null},metadata:meta()};
}
function standaloneUsage(req){const u=Math.max(1,Number(req.estimated_users||1));return {api_requests:u*45,lambda_requests:u*55,lambda_memory_mb:512,lambda_duration_ms:u>100000?400:250,storage_gb_month:Math.max(1,u*.008),dynamodb_read_units:u*120,dynamodb_write_units:u*30,internet_transfer_gb:Math.max(.5,u*.0075),cloudfront_requests:u*35,log_ingest_gb:Math.max(.1,u*45/1000000*2.5),backup_gb_month:Math.max(.5,u*.004),waf_requests:u*45,email_messages:u*2,active_users:u,events_messages:u*6,container_vcpu_hours:Math.max(1,u/1000*15),instance_hours:730,database_instance_hours:730,cache_instance_hours:730,stream_shard_hours:730,analytics_tb_scanned:Math.max(.001,u*.00001),ml_endpoint_hours:Math.min(730,Math.max(1,u/100)),genai_input_k_tokens:Math.max(1,u*4),genai_output_k_tokens:Math.max(1,u*1.2)};}
function standaloneBadges(a){return [{id:'sector-guru',name:'Sector Guru',description:'Workload signals mapped to a concrete architecture type',earned:true},{id:'aws-explorer',name:'AWS Explorer',description:'Architecture evaluates at least six AWS services',earned:a.services.length>=6},{id:'well-architected',name:'Well-Architected',description:'All six Well-Architected pillars have an explicit review state',earned:(a.well_architected||[]).length===6},{id:'cost-analyst',name:'Cost Analyst',description:'Explicit usage quantities are available for pricing',earned:true}];}
export function standaloneAnalysis(req){const a=baseStandaloneAnalysis(req),t=a.cost_analysis.summary.typical_value;a.usage_profile=standaloneUsage(req);a.scenarios=[{name:'essential',title:'Essential',availability_target:'Managed single-region baseline',usage_multiplier:.75,service_ids:a.services.filter((_,i)=>i<Math.max(5,Math.ceil(a.services.length*.7))).map(x=>x.id),monthly_planning_cost:+(t*.75).toFixed(2),rationale:['Minimum managed-service footprint','Preserves the core product path'],tradeoffs:['Lower redundancy and fewer specialist controls']},{name:'balanced',title:'Balanced',availability_target:'Production-oriented single-region baseline',usage_multiplier:1,service_ids:a.services.map(x=>x.id),monthly_planning_cost:+t.toFixed(2),rationale:['Balances cost, security and operations'],tradeoffs:['Multi-region DR remains a separate decision']},{name:'resilient',title:'Resilient',availability_target:'Stronger recovery, observability and security controls',usage_multiplier:1.45,service_ids:[...new Set([...a.services.map(x=>x.id),'cloudwatch','waf','kms','route53'])],monthly_planning_cost:+(t*1.45).toFixed(2),rationale:['Prioritizes recovery and operational evidence'],tradeoffs:['Higher recurring cost and operational complexity']}];a.architecture_decisions=[{id:'ADR-001',title:'Prefer managed services where they reduce undifferentiated operations',status:'accepted',decision:'Use managed/serverless primitives unless workload constraints explicitly require host or cluster control.',alternatives:['Long-lived EC2 fleet','Self-managed Kubernetes'],consequences:['Lower operational burden','Service quotas, regional availability and pricing remain design inputs']}];a.optimization_suggestions=[{id:'opt-budget',title:'Budget and anomaly guardrails',category:'cost',impact:'high',recommendation:'Create budgets and anomaly monitors before production.',estimated_savings_percent:8},{id:'opt-restore',title:'Measure restore time',category:'reliability',impact:'high',recommendation:'Run restore drills and record observed RPO/RTO.',estimated_savings_percent:null},{id:'opt-rightsize',title:'Right-size after observing real utilization',category:'performance-cost',impact:'medium',recommendation:'Compare measured traffic and latency with the explicit usage model before committing capacity.',estimated_savings_percent:12}];a.badges=standaloneBadges(a);a.pricing_provenance=[{state:'planning_baseline',source:'awsfc-embedded-pricing-2026-10-09',region:req.region,currency:'USD',acquired_at:nowIso(),effective_at:null,fallback_reason:'Standalone mode uses a versioned local pricing snapshot; the AWS connector is optional'}];a.marketplace_links=Object.fromEntries(a.services.map(x=>[x.id,`https://aws.amazon.com/marketplace/search/results?searchTerms=${encodeURIComponent(x.name)}`]));return a;}

function quantityMap(u={}){return {lambda:(u.lambda_requests||0)+(u.lambda_requests||0)*(u.lambda_memory_mb||512)/1024*(u.lambda_duration_ms||250)/1000,'api-gateway':u.api_requests||0,dynamodb:(u.dynamodb_read_units||0)+(u.dynamodb_write_units||0),s3:u.storage_gb_month||0,cloudfront:u.cloudfront_requests||0,cognito:Math.max(0,(u.active_users||0)-10000),cloudwatch:u.log_ingest_gb||0,waf:u.waf_requests||0,sqs:u.events_messages||0,eventbridge:u.events_messages||0,ses:u.email_messages||0,'ecs-fargate':u.container_vcpu_hours||0,eks:1,ec2:u.instance_hours||0,rds:u.database_instance_hours||0,aurora:u.database_instance_hours||0,elasticache:u.cache_instance_hours||0,sns:u.events_messages||0,'step-functions':(u.events_messages||0)*4,kinesis:u.stream_shard_hours||0,opensearch:u.instance_hours||0,glue:Math.max(0,(u.analytics_tb_scanned||0)*4),athena:u.analytics_tb_scanned||0,redshift:u.database_instance_hours||0,quicksight:Math.max(1,(u.active_users||0)/20),sagemaker:u.ml_endpoint_hours||0,bedrock:(u.genai_input_k_tokens||0)+(u.genai_output_k_tokens||0),'iot-core':u.events_messages||0,route53:1,acm:0,kms:1,'secrets-manager':3,xray:(u.api_requests||0)/1000000,appsync:u.api_requests||0,efs:u.storage_gb_month||0,shield:0,'iam-identity-center':0};}
const TRANSFER_BASELINE={cloudfront_to_internet:[[0,10240,.085],[10240,51200,.080],[51200,null,.060]],aws_service_to_internet:[[0,10240,.09],[10240,null,.085]],cross_az:[[0,null,.01]],inter_region:[[0,null,.02]],s3_to_cloudfront:[[0,null,0]]};
function transferTierLines(path,catalog){const rule=String(path?.rule||''),tiers=TRANSFER_BASELINE[rule],quantity=Number(path?.quantity_gb);if(!tiers)throw Object.assign(new Error(`Unsupported transfer pricing rule: ${rule||'(blank)'}`),{status:422});if(!Number.isFinite(quantity)||quantity<0)throw Object.assign(new Error('Transfer quantity_gb must be a non-negative number'),{status:422});const lines=[];for(const [begin,end,price] of tiers){const capacity=end===null?Infinity:Math.max(0,end-begin),tierQuantity=end===null?Math.max(0,quantity-begin):Math.min(Math.max(0,quantity-begin),capacity);if(tierQuantity<=0)continue;lines.push({service_id:'data-transfer',dimension:rule,unit:'GB',quantity:+quantity.toFixed(8),begin_range:begin,end_range:end,tier_quantity:+tierQuantity.toFixed(8),unit_price:price,region_multiplier:1,partial_cost:+(tierQuantity*price).toFixed(6),sku:null,rate_code:null,effective_at:catalog.published_at||null,acquired_at:catalog.imported_at||catalog.updated_at||nowIso(),source:'awsfc-transfer-baseline-v2',fallback_reason:rule==='s3_to_cloudfront'?null:'Transfer planning baseline; verify current AWS terms before commercial use'});}return lines;}
function pricingFreshness(catalog={}){const published=Date.parse(catalog.published_at||catalog.updated_at||''),valid=Date.parse(catalog.valid_until||'');if(Number.isFinite(valid)&&Date.now()>valid)return 'expired';if(!Number.isFinite(published))return 'unknown';const age=(Date.now()-published)/86400000;return age<=30?'fresh':age<=90?'aging':'stale';}
function standalonePricing(req,catalog={}){if(req.strict_authoritative)throw Object.assign(new Error('Authoritative Price List pricing cannot be guaranteed in Standalone mode. Use the optional AWS connector.'),{status:409});const u=req.usage||{},services=[...new Set(req.service_ids?.length?req.service_ids:['lambda','api-gateway','dynamodb','s3','cloudfront','cognito','cloudwatch'])],rates=catalog.rates||{},qty=quantityMap(u),region=req.region||'us-east-1';if(catalog.currency&&String(catalog.currency).toUpperCase()!=='USD')throw Object.assign(new Error('Standalone pricing snapshots must use USD to remain compatible with the public pricing contract.'),{status:422});if(catalog.region_multipliers&&Object.keys(catalog.region_multipliers).length&&!Object.prototype.hasOwnProperty.call(catalog.region_multipliers,region))throw Object.assign(new Error(`Pricing snapshot ${catalog.version||'(unknown)'} has no region multiplier for ${region}.`),{status:422});const regionMult=Number(catalog.region_multipliers?.[region]??1);const missing=services.filter(id=>!Object.prototype.hasOwnProperty.call(rates,id));if(missing.length)throw Object.assign(new Error(`Pricing snapshot ${catalog.version||'(unknown)'} has no rate for: ${missing.join(', ')}`),{status:422});const lines=services.map(id=>{const q=Number(qty[id]||0),rate=Number(rates[id]),partial=q*rate*regionMult;return {service_id:id,dimension:'standalone-planning-dimension',unit:'unit',quantity:q,begin_range:0,end_range:null,tier_quantity:q,unit_price:rate,region_multiplier:regionMult,partial_cost:+partial.toFixed(6),sku:null,rate_code:null,effective_at:catalog.published_at||null,acquired_at:catalog.imported_at||catalog.updated_at||nowIso(),source:catalog.version||'embedded',fallback_reason:'Versioned standalone planning snapshot; not an authoritative AWS Price List quote'}});for(const path of (req.transfer_paths||[]))lines.push(...transferTierLines(path,catalog));return {quote_id:uid('quote'),region,currency:'USD',source_state:'planning_baseline',snapshot_kind:'embedded_snapshot',freshness_state:pricingFreshness(catalog),catalog_version:catalog.version||'embedded',total_monthly:+lines.reduce((a,b)=>a+b.partial_cost,0).toFixed(6),lines,provenance:[{state:'planning_baseline',source:catalog.version||'embedded',region,currency:'USD',acquired_at:catalog.imported_at||catalog.updated_at||nowIso(),effective_at:catalog.published_at||null,fallback_reason:'Versioned standalone planning snapshot; use the AWS connector for authoritative live Price List evidence'}],assumptions:['Standalone pricing is a planning model, not an AWS quotation.','Check catalog freshness before commercial decisions.','Data-transfer paths are priced with explicit revisioned planning tiers when provided.','Private discounts, commitments, credits and taxes are never invented in Standalone mode.'],metadata:meta()};}
function projectReq(p,override={}){return {description:override.description??p.description,estimated_users:override.estimated_users??p.estimated_users,budget:override.budget??p.budget,region:override.region??p.region,advanced_guide:override.advanced_guide??true}}
function validateCatalog(p){if(!p||typeof p!=='object'||!p.rates||typeof p.rates!=='object')throw Object.assign(new Error('Pricing snapshot must contain a rates object'),{status:422});const currency=String(p.currency||'USD').toUpperCase();if(currency!=='USD')throw Object.assign(new Error('Pricing snapshot currency must be USD'),{status:422});const rates={};for(const [k,v] of Object.entries(p.rates)){const n=Number(v);if(!k||!Number.isFinite(n)||n<0)throw Object.assign(new Error(`Invalid rate for ${k}`),{status:422});rates[k]=n}const region_multipliers={};for(const [k,v] of Object.entries(p.region_multipliers||{})){const n=Number(v);if(!k||!Number.isFinite(n)||n<=0||n>10)throw Object.assign(new Error(`Invalid region multiplier for ${k}`),{status:422});region_multipliers[k]=n}return {version:String(p.version||`custom-${Date.now()}`).slice(0,120),source:String(p.source||'imported_snapshot').slice(0,80),currency:'USD',published_at:p.published_at||null,valid_until:p.valid_until||null,updated_at:p.updated_at||p.published_at||null,imported_at:nowIso(),rates,region_multipliers}}

export const standaloneApi={
  async health(){const info=await vaultInfo();return {status:'healthy',check:'readiness',timestamp:nowIso(),version:APP_VERSION,release_version:WEB_VERSION,git_sha:'standalone-browser',environment:'standalone',api_version:'v1',persistence_backend:info.storage,persistence_status:'available',network_required:false}},
  async me(){return {subject:'local-owner',username:'Local Owner',metadata:meta()}},
  async createTenant(payload){const s=await loadVault();if(s.tenant)throw Object.assign(new Error('A standalone vault already has a workspace. Reset it or restore another backup first.'),{status:409});const name=String(payload.name||'').trim();if(name.length<2)throw Object.assign(new Error('Workspace name must contain at least 2 characters'),{status:422});const t={id:uid('tenant'),name,slug:String(payload.slug||name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')).slice(0,80),status:'active',created_at:nowIso(),updated_at:nowIso(),revision:1};s.tenant=t;s.memberships=[{tenant_id:t.id,subject:'local-owner',role:'owner',status:'active',created_at:nowIso(),updated_at:nowIso(),revision:1,local_only:true}];audit(s,'tenant.created','tenant',t.id);await saveVault(s);return {tenant:t,metadata:meta()}},
  async getTenant(id){const s=await loadVault();if(!s.tenant||s.tenant.id!==id)throw Object.assign(new Error('Workspace not found'),{status:404});return {tenant:s.tenant,metadata:meta()}},
  async listMemberships(id,paging={}){const s=await loadVault();if(s.tenant?.id!==id)throw Object.assign(new Error('Workspace not found'),{status:404});const r=page(s.memberships,paging);return {memberships:r.values,next_cursor:r.next_cursor,security_boundary:'Standalone roles are organizational labels, not an authentication boundary.',metadata:meta()}},
  async createMembership(id,p){const s=await loadVault();if(s.tenant?.id!==id)throw Object.assign(new Error('Workspace not found'),{status:404});if(p.role==='owner')throw Object.assign(new Error('Owner grants require a dedicated transfer workflow'),{status:409});const subject=String(p.subject||'').trim();if(!subject)throw Object.assign(new Error('Member label is required'),{status:422});if(s.memberships.some(x=>x.subject===subject))throw Object.assign(new Error('Member label already exists'),{status:409});const m={tenant_id:id,subject,role:['viewer','editor','admin'].includes(p.role)?p.role:'viewer',status:'active',created_at:nowIso(),updated_at:nowIso(),revision:1,local_only:true};s.memberships.push(m);audit(s,'membership.created','membership',subject,{role:m.role,local_only:true});await saveVault(s);return {membership:m,metadata:meta()}},
  async updateMembership(id,subject,p){const s=await loadVault(),m=s.memberships.find(x=>x.subject===subject);if(s.tenant?.id!==id||!m)throw Object.assign(new Error('Membership not found'),{status:404});if(m.role==='owner'||p.role==='owner')throw Object.assign(new Error('Owner role is immutable in the generic membership API'),{status:409});if(Number(p.expected_revision)!==m.revision)throw Object.assign(new Error('Revision conflict'),{status:409});if(p.role)m.role=p.role;if(p.status)m.status=p.status;m.revision++;m.updated_at=nowIso();audit(s,'membership.updated','membership',subject,{...p,local_only:true});await saveVault(s);return {membership:m,metadata:meta()}},
  async listAudit(id,paging={}){const s=await loadVault();if(s.tenant?.id!==id)throw Object.assign(new Error('Workspace not found'),{status:404});const r=page(s.audit,paging);return {audit_events:r.values,next_cursor:r.next_cursor,security_boundary:'Local audit is user-controlled browser data. Backup SHA-256 detects accidental/post-export modification only; it is not a tamper-proof ledger or CloudTrail.',metadata:meta()}},
  async createProject(p){const s=await loadVault();if(!s.tenant)throw Object.assign(new Error('Create a workspace first'),{status:409});const name=String(p.name||'').trim(),description=String(p.description||'').trim(),users=Number(p.estimated_users);if(name.length<2||description.length<10||!Number.isFinite(users)||users<1)throw Object.assign(new Error('Project requires a valid name, description and positive user estimate'),{status:422});const pr={id:uid('project'),tenant_id:s.tenant.id,name,description,estimated_users:users,budget:['low','medium','high'].includes(p.budget)?p.budget:'medium',region:String(p.region||'us-east-1'),status:['draft','active','archived'].includes(p.status)?p.status:'draft',created_at:nowIso(),updated_at:nowIso(),revision:1};s.projects.unshift(pr);audit(s,'project.created','project',pr.id);await saveVault(s);return {project:pr,metadata:meta()}},
  async listProjects(paging={}){const r=page((await loadVault()).projects,paging);return {projects:r.values,next_cursor:r.next_cursor,metadata:meta()}},
  async getProject(id){return {project:ensureProject(await loadVault(),id),metadata:meta()}},
  async updateProject(id,payload){const s=await loadVault(),p=ensureProject(s,id);if(Number(payload.expected_revision)!==p.revision)throw Object.assign(new Error('Revision conflict'),{status:409});for(const [k,v] of Object.entries(payload)){if(k==='expected_revision'||v===undefined||v===null)continue;if(k==='status'&&!['draft','active','archived'].includes(v))continue;p[k]=v}p.revision++;p.updated_at=nowIso();audit(s,'project.updated','project',id,payload);await saveVault(s);return {project:p,metadata:meta()}},
  async createProjectAnalysis(id,payload={}){const s=await loadVault(),p=ensureProject(s,id);if(p.status==='archived')throw Object.assign(new Error('Archived projects cannot receive new analysis versions'),{status:409});const result=standaloneAnalysis(projectReq(p,payload));if(result.pricing_provenance?.[0])result.pricing_provenance[0].source=s.pricingCatalog?.version||result.pricing_provenance[0].source;const list=s.analyses[id]||[],version=Math.max(0,...list.map(x=>Number(x.version)||0))+1,v={analysis_id:uid('analysis'),tenant_id:p.tenant_id,project_id:id,version,request:projectReq(p,payload),result:{...result,project_id:id},created_at:nowIso()};list.unshift(v);s.analyses[id]=list;audit(s,'analysis.created','analysis',v.analysis_id,{project_id:id,version:v.version,knowledge_version:KNOWLEDGE_VERSION});await saveVault(s);return {analysis_version:v,metadata:meta()}},
  async listProjectAnalyses(id,paging={}){ensureProject(await loadVault(),id);const s=await loadVault(),r=page(s.analyses[id]||[],paging);return {analysis_versions:r.values.map(v=>({analysis_id:v.analysis_id,project_id:id,version:v.version,project_type:v.result.analysis.project_type,typical_monthly_cost:v.result.cost_analysis.summary.typical,created_at:v.created_at})),next_cursor:r.next_cursor,metadata:meta()}},
  async getProjectAnalysis(id,version){const s=await loadVault(),v=(s.analyses[id]||[]).find(x=>x.version===Number(version));if(!v)throw Object.assign(new Error('Analysis version not found'),{status:404});return {analysis_version:v,metadata:meta()}},
  async analyze(req){const s=await loadVault(),r=standaloneAnalysis(req);if(r.pricing_provenance?.[0])r.pricing_provenance[0].source=s.pricingCatalog?.version||r.pricing_provenance[0].source;return r},
  async iac(req){const a=standaloneAnalysis(req),services=a.services.map(x=>x.name),main=`terraform {\n  required_providers { aws = { source = "hashicorp/aws" version = "~> 5.0" } }\n}\nprovider "aws" { region = var.aws_region }\n\n# Standalone planning baseline generated by AWS Friendly Counsellor\n# Selected services: ${services.join(', ')}\n\nresource "aws_cognito_user_pool" "users" {\n  name = "awsfc-users"\n  mfa_configuration = "OPTIONAL"\n  software_token_mfa_configuration { enabled = true }\n}\n`;return {project_id:uid('iac'),analysis:{project_type:a.analysis.project_type,services_count:services.length,region:req.region},terraform:{format:'terraform',status:'baseline_ready',supported_services:services,deferred_services:[],files:{'main.tf':main,'variables.tf':`variable "aws_region" { type = string default = "${req.region}" }\n`,'outputs.tf':'output "user_pool_id" { value = aws_cognito_user_pool.users.id }\n','README.md':'# Generated baseline\nReview IAM, networking, data retention, quotas, service mappings and cost assumptions before deployment.\n'},instructions:['Run terraform fmt','Run terraform validate','Review terraform plan','Apply first in an isolated non-production account']},metadata:meta()}},
  async narrative(req){const a=standaloneAnalysis(req),rows=a.services.map(s=>`<tr><td>${s.name}</td><td>${s.category}</td><td>${s.why_needed}</td><td>${s.typical_monthly}</td></tr>`).join(''),risks=(a.architecture_risks||[]).map(r=>`<li><strong>${r.severity}</strong> — ${r.title}: ${r.recommendation}</li>`).join('');return {project_id:uid('narrative'),narrative_html:`<h1>AWS Friendly Counsellor architecture report</h1><p><strong>Project type:</strong> ${a.analysis.project_type}</p><p><strong>Region:</strong> ${req.region}</p><p><strong>Estimated users:</strong> ${Number(req.estimated_users).toLocaleString()}</p><p><strong>Knowledge base:</strong> ${KNOWLEDGE_VERSION}</p><h2>Recommended services</h2><table><thead><tr><th>Service</th><th>Category</th><th>Why</th><th>Planning cost</th></tr></thead><tbody>${rows}</tbody></table><h2>Architecture risks</h2><ul>${risks||'<li>No high-signal risk rule fired; validate manually.</li>'}</ul><h2>Cost range</h2><p>${a.cost_analysis.summary.minimum} – ${a.cost_analysis.summary.maximum} monthly planning range.</p><h2>Implementation</h2><ol>${a.implementation_guide.phases.map(p=>`<li><strong>${p.name}</strong> — ${p.steps.join('; ')}</li>`).join('')}</ol><p><em>Generated locally. Connect AWS only when live account evidence is required.</em></p>`,metadata:meta()}},
  async pricingStatus(){const state=await loadVault(),catalog=state.pricingCatalog||{};return {dynamic_pricing_enabled:false,strict_mode:false,cache_ttl_seconds:86400,circuit_open_seconds:120,circuit_state:'closed',source_state:'planning_baseline',snapshot_kind:'embedded_snapshot',freshness_state:pricingFreshness(catalog),catalog_version:catalog.version||'embedded',catalog_updated_at:catalog.updated_at||null,catalog_valid_until:catalog.valid_until||null,supported_service_ids:Object.keys(catalog.rates||{}),metadata:meta()}},
  async pricingQuote(req){const state=await loadVault();return standalonePricing(req,state.pricingCatalog)},
  async simulateRegions(req){const state=await loadVault(),catalog=state.pricingCatalog||{};return {simulations:(req.regions||['us-east-1','eu-west-1','ap-southeast-1']).map(region=>{const q=standalonePricing({...req,region},catalog);return {region,total_monthly:q.total_monthly,source_state:q.source_state,freshness_state:q.freshness_state}}),metadata:meta()}},
  async getWorkspace(id,v){const s=await loadVault(),x=(s.analyses[id]||[]).find(a=>a.version===Number(v));if(!x)throw Object.assign(new Error('Workspace not found'),{status:404});return {workspace:{...x,usage_profile:x.result.usage_profile,scenarios:x.result.scenarios,architecture_decisions:x.result.architecture_decisions,optimization_suggestions:x.result.optimization_suggestions,badges:x.result.badges,pricing_provenance:x.result.pricing_provenance,marketplace_links:x.result.marketplace_links,architecture_risks:x.result.architecture_risks,well_architected:x.result.well_architected},metadata:meta()}},
  async getReportBundle(id,v){const x=((await loadVault()).analyses[id]||[]).find(a=>a.version===Number(v));if(!x)throw Object.assign(new Error('Workspace not found'),{status:404});const snapshot=JSON.stringify(x),hash=await sha256Hex(snapshot),report=(await this.narrative(x.request)).narrative_html,prov={project_id:id,workspace_version:Number(v),analysis_id:x.analysis_id,workspace_sha256:hash,generated_at:nowIso(),contract_version:'1.13.0',knowledge_version:KNOWLEDGE_VERSION};return {project_id:id,workspace_version:Number(v),workspace_sha256:hash,narrative_html:report,files:{'report.html':report,'analysis-snapshot.json':JSON.stringify(x,null,2),'architecture-decisions.json':JSON.stringify(x.result.architecture_decisions||[],null,2),'well-architected.json':JSON.stringify(x.result.well_architected||[],null,2),'PROVENANCE.json':JSON.stringify(prov,null,2)},metadata:meta()}},
  async createAccountEstimate(id,v,p){const s=await loadVault(),analysis=(s.analyses[id]||[]).find(a=>a.version===Number(v));if(!analysis)throw Object.assign(new Error('Workspace not found'),{status:404});const quote=standalonePricing({region:analysis.request.region,usage:analysis.result.usage_profile,service_ids:analysis.result.services.map(x=>x.id)},s.pricingCatalog),eid=uid('est'),account=quote.total_monthly,now=nowIso(),ttl=Math.max(1,Math.min(365,Number(p.ttl_days)||30)),exp=new Date(Date.now()+ttl*86400000).toISOString(),row={estimate_id:eid,tenant_id:s.tenant?.id||'local',project_id:id,workspace_version:Number(v),account_id:'000000000000',aws_estimate_id:null,provider:'local_public_snapshot',rate_type:'BEFORE_DISCOUNTS',requested_rate_type:p.rate_type||'BEFORE_DISCOUNTS',discount_model:'none',status:'VALID',public_monthly:quote.total_monthly,account_monthly:account,delta:0,delta_percent:0,reconciliation:'aligned',tolerance_percent:5,expires_at:exp,revision:1,created_at:now,updated_at:now,failure_message:null,catalog_version:quote.catalog_version,freshness_state:quote.freshness_state,note:'Standalone never invents AWS account/private discounts; account-aware rates require the optional AWS connector.'};s.accountEstimates[eid]=row;s.accountEstimateRevisions[eid]=[clone(row)];audit(s,'local_estimate.created','account_estimate',eid,{discount_model:'none'});await saveVault(s);return {estimate:row,metadata:meta()}},
  async listAccountEstimates(id,paging={}){const rows=Object.values((await loadVault()).accountEstimates).filter(x=>x.project_id===id).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)));const r=page(rows,paging);return {estimates:r.values,next_cursor:r.next_cursor,metadata:meta()}},
  async listAccountEstimateRevisions(id,eid){const s=await loadVault(),x=s.accountEstimates[eid];if(!x||x.project_id!==id)throw Object.assign(new Error('Estimate not found'),{status:404});return {revisions:s.accountEstimateRevisions[eid]||[clone(x)],metadata:meta()}},
  async refreshAccountEstimate(id,eid){const s=await loadVault(),x=ensureEstimate(s,id,eid),analysis=(s.analyses[id]||[]).find(a=>a.version===x.workspace_version);if(!analysis)throw Object.assign(new Error('Workspace not found'),{status:404});const q=standalonePricing({region:analysis.request.region,usage:analysis.result.usage_profile,service_ids:analysis.result.services.map(v=>v.id)},s.pricingCatalog);x.public_monthly=q.total_monthly;x.account_monthly=q.total_monthly;x.delta=0;x.delta_percent=0;x.reconciliation='aligned';x.provider='local_public_snapshot';x.rate_type='BEFORE_DISCOUNTS';x.discount_model='none';x.catalog_version=q.catalog_version;x.freshness_state=q.freshness_state;x.revision++;x.updated_at=nowIso();(s.accountEstimateRevisions[eid]||=[]).push(clone(x));audit(s,'local_estimate.refreshed','account_estimate',eid,{discount_model:'none'});await saveVault(s);return {estimate:x,metadata:meta()}},
  async extendAccountEstimate(id,eid,p){const s=await loadVault(),x=ensureEstimate(s,id,eid);if(Number(p.expected_revision)!==x.revision)throw Object.assign(new Error('Revision conflict'),{status:409});x.expires_at=new Date(Date.now()+Math.max(1,Math.min(365,Number(p.ttl_days)||30))*86400000).toISOString();x.revision++;x.updated_at=nowIso();(s.accountEstimateRevisions[eid]||=[]).push(clone(x));audit(s,'local_estimate.extended','account_estimate',eid);await saveVault(s);return {estimate:x,metadata:meta()}},
  async listActualCosts(id,paging={}){const rows=Object.values((await loadVault()).actualCosts).filter(x=>x.project_id===id).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)));const r=page(rows,paging);return {snapshots:r.values,next_cursor:r.next_cursor,metadata:meta()}},
  async listActualCostRevisions(id,sid){const s=await loadVault(),x=s.actualCosts[sid];if(!x||x.project_id!==id)throw Object.assign(new Error('Snapshot not found'),{status:404});return {revisions:s.actualCostRevisions[sid]||[clone(x)],metadata:meta()}},
  async refreshActualCost(id,sid){const s=await loadVault(),x=s.actualCosts[sid];if(!x||x.project_id!==id)throw Object.assign(new Error('Snapshot not found'),{status:404});if(x.source!=='local_manual')throw Object.assign(new Error('Imported CUR snapshots are immutable; import a corrected snapshot instead.'),{status:409});x.actual_total=Number(x.actual_total);x.drift=+(x.actual_total-Number(x.forecast_total||0)).toFixed(6);x.drift_percent=x.forecast_total?+(x.drift/Number(x.forecast_total)*100).toFixed(4):null;x.drift_state=Math.abs(x.drift_percent||0)<=10?'aligned':x.drift<0?'under_forecast':'over_forecast';x.severity=x.drift>0&&x.drift_percent>=20?'critical':x.drift>0&&x.drift_percent>=10?'warning':'none';x.captured_at=nowIso();x.revision++;x.updated_at=nowIso();(s.actualCostRevisions[sid]||=[]).push(clone(x));audit(s,'actual_cost_snapshot.refreshed','actual_cost',sid);await saveVault(s);return {snapshot:x,metadata:meta()}},
  async createActualCost(id,p){const s=await loadVault(),e=ensureEstimate(s,id,p.estimate_id);if(!validDateRange(p.start_date,p.end_date))throw Object.assign(new Error('Actual-cost date range must have start < end'),{status:422});const sid=uid('acs'),actual=Number(p.actual_total),forecast=Number(e.account_monthly||e.public_monthly);if(!Number.isFinite(actual)||actual<0)throw Object.assign(new Error('actual_total must be a non-negative number'),{status:422});const delta=actual-forecast,pct=forecast?delta/forecast*100:null,now=nowIso(),x={snapshot_id:sid,tenant_id:s.tenant?.id||'local',project_id:id,workspace_version:e.workspace_version,estimate_id:e.estimate_id,account_id:p.account_id||'000000000000',source:'local_manual',start_date:p.start_date,end_date:p.end_date,metric:p.metric||'UnblendedCost',currency:'USD',project_tag_key:'AWSFCProjectId',project_tag_value:id,billing_view_arn:null,estimated:false,status:'final',captured_at:now,daily_costs:[{date:p.start_date,service:'Local actual-cost aggregate',amount:actual,currency:'USD',estimated:false,status:'final'}],actual_total:actual,forecast_total:forecast,drift:+delta.toFixed(6),drift_percent:pct===null?null:+pct.toFixed(4),drift_state:Math.abs(pct||0)<=10?'aligned':delta<0?'under_forecast':'over_forecast',severity:delta>0&&pct>=20?'critical':delta>0&&pct>=10?'warning':'none',services:[{service:'Local actual-cost aggregate',amount:actual,currency:'USD'}],query_pages:0,api_request_count:0,query_cost_usd:0,revision:1,created_at:now,updated_at:now};s.actualCosts[sid]=x;s.actualCostRevisions[sid]=[clone(x)];audit(s,'actual_cost_snapshot.created','actual_cost',sid);await saveVault(s);return {snapshot:x,metadata:meta()}},
  async importCur2(id,p){const s=await loadVault(),e=ensureEstimate(s,id,p.estimate_id);if(!validDateRange(p.start_date,p.end_date))throw Object.assign(new Error('CUR date range must have start < end'),{status:422});if(!Array.isArray(p.rows)||!p.rows.length)throw Object.assign(new Error('CUR import requires at least one row'),{status:422});if(p.rows.length>500)throw Object.assign(new Error('CUR import accepts at most 500 aggregated rows per snapshot; stream/aggregate the source file first.'),{status:422});const normalized=[];for(const r of p.rows){const amount=Number(r.amount??r.cost);if(!Number.isFinite(amount)||amount<0)throw Object.assign(new Error('CUR rows require non-negative numeric amount/cost values'),{status:422});const date=String(r.date||p.start_date).slice(0,10),currency=String(r.currency||'USD').toUpperCase().slice(0,8);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||date<p.start_date||date>=p.end_date)throw Object.assign(new Error(`CUR row date ${date||'(blank)'} is outside the selected [start, end) window`),{status:422});if(currency!=='USD')throw Object.assign(new Error(`CUR row currency ${currency} cannot be mixed into a USD snapshot`),{status:422});normalized.push({date,service:String(r.service||'Unspecified service').slice(0,256),amount,currency:'USD',estimated:!!r.estimated})}const total=normalized.reduce((a,b)=>a+b.amount,0),sid=uid('acs'),forecast=Number(e.account_monthly||e.public_monthly),delta=total-forecast,pct=forecast?delta/forecast*100:null,now=nowIso(),estimated=normalized.some(r=>r.estimated),byService=new Map();for(const r of normalized)byService.set(r.service,(byService.get(r.service)||0)+r.amount);const x={snapshot_id:sid,tenant_id:s.tenant?.id||'local',project_id:id,workspace_version:e.workspace_version,estimate_id:e.estimate_id,account_id:'000000000000',source:'cur_2_0_import',start_date:p.start_date,end_date:p.end_date,metric:'CUR2AggregatedCost',currency:'USD',project_tag_key:'AWSFCProjectId',project_tag_value:id,billing_view_arn:null,estimated,status:estimated?'estimated':'final',captured_at:now,daily_costs:normalized.map(r=>({...r,status:r.estimated?'estimated':'final'})),actual_total:+total.toFixed(6),forecast_total:forecast,drift:+delta.toFixed(6),drift_percent:pct===null?null:+pct.toFixed(4),drift_state:Math.abs(pct||0)<=10?'aligned':delta<0?'under_forecast':'over_forecast',severity:delta>0&&pct>=20?'critical':delta>0&&pct>=10?'warning':'none',services:[...byService.entries()].map(([service,amount])=>({service,amount:+amount.toFixed(6),currency:'USD'})),query_pages:0,api_request_count:0,query_cost_usd:0,revision:1,created_at:now,updated_at:now,import_stats:p.import_stats||null};s.actualCosts[sid]=x;s.actualCostRevisions[sid]=[clone(x)];audit(s,'cur_snapshot.imported','actual_cost',sid,{rows:normalized.length,stats:p.import_stats||null});await saveVault(s);return {snapshot:x,metadata:meta()}},
  async gamification(){const s=await loadVault(),leaderboard=s.projects.map(p=>{const a=(s.analyses[p.id]||[])[0],badges=a?.result?.badges||[],earned=badges.filter(b=>b.earned).length;return {project_id:p.id,project_name:p.name,earned_badges:earned,latest_score:earned*25+(a?.result?.analysis?.confidence||0)*10}}).sort((a,b)=>b.latest_score-a.latest_score),all=[];for(const p of s.projects)for(const b of ((s.analyses[p.id]||[])[0]?.result?.badges||[]))if(b.earned&&!all.some(x=>x.id===b.id))all.push(b);return {badges:all,leaderboard,metadata:meta()}},
  async privacyExport(){const s=await loadVault(),m=s.memberships.find(x=>x.subject==='local-owner');return {subject:'local-owner',tenant_id:s.tenant?.id||'local',membership:m||null,authored_audit_events:s.audit.filter(x=>x.actor_subject==='local-owner'),local_data_summary:{projects:s.projects.length,analyses:Object.values(s.analyses).reduce((n,a)=>n+a.length,0),estimates:Object.keys(s.accountEstimates).length,actual_cost_snapshots:Object.keys(s.actualCosts).length},generated_at:nowIso(),metadata:meta()}},
  async privacyDelete(){const s=await loadVault(),rid=uid('pdr'),x={request_id:rid,tenant_id:s.tenant?.id||'local',subject:'local-owner',status:'ready_for_local_reset',created_at:nowIso(),updated_at:nowIso(),revision:1,note:'Standalone data is stored only in this browser. Confirm local vault reset to complete erasure; exported backups are outside the application and must be deleted separately.'};s.privacyRequests.push(x);await saveVault(s);return {deletion_request:x,metadata:meta()}},
  async pricingCatalog(){const s=await loadVault();return {catalog:clone(s.pricingCatalog),freshness_state:pricingFreshness(s.pricingCatalog),metadata:meta()}},
  async importPricingCatalog(payload){const s=await loadVault(),p=typeof payload==='string'?JSON.parse(payload):payload,catalog=validateCatalog(p);s.pricingCatalog=catalog;audit(s,'pricing_catalog.imported','pricing_catalog',catalog.version,{freshness_state:pricingFreshness(catalog)});await saveVault(s);return {catalog:clone(catalog),freshness_state:pricingFreshness(catalog),metadata:meta()}},
  async backupExport(){return exportVault()},
  async backupExportEncrypted(passphrase){return exportEncryptedVault(passphrase)},
  async backupImport(payload,passphrase=''){const parsed=typeof payload==='string'?JSON.parse(payload):payload,state=parsed?.format==='awsfc-local-backup-encrypted'?await importEncryptedVault(parsed,passphrase):await importVault(parsed);return {status:'imported',tenant_id:state.tenant?.id||null,projects:state.projects.length,metadata:meta()}},
  async backupStatus(){return {...backupStatus(),metadata:meta()}},
  async recoveryList(){return {checkpoints:await recoveryList(),metadata:meta()}},
  async recoveryRestore(id){const state=await recoveryRestore(id);return {status:'restored',tenant_id:state.tenant?.id||null,projects:state.projects.length,metadata:meta()}},
  async requestPersistentStorage(){return {...await requestPersistentStorage(),metadata:meta()}},
  async resetLocalData(){await resetVault();return {status:'reset',metadata:meta()}},
  async storageInfo(){return {...await vaultInfo(),metadata:meta()}}
};
