// Local-first persistence layer. IndexedDB is primary; localStorage is a fallback.
// Schema v2 adds optimistic concurrency, bounded recovery checkpoints, backup
// integrity metadata and optional encrypted portable backups.
const DB_NAME='awsfc-local-vault';
const DB_VERSION=2;
const STORE='kv';
const RECOVERY_STORE='recovery';
const STATE_KEY='state';
const FALLBACK_KEY='awsfc.standalone.v2';
const LEGACY_KEYS=['awsfc.standalone.v1','awsfc.demo.v2'];
const HISTORY_KEY='awsfc.standalone.recovery.v2';
const META_KEY='awsfc.standalone.meta.v2';
const MAX_RECOVERY=8;
const MAX_RECOVERY_SNAPSHOT_BYTES=5*1024*1024;
let localQueue=Promise.resolve();

const defaultPricing=()=>({version:'awsfc-embedded-pricing-2026-10-09',source:'embedded_snapshot',currency:'USD',published_at:'2026-10-09T00:00:00Z',valid_until:'2027-01-09T00:00:00Z',updated_at:'2026-10-09T00:00:00Z',rates:{lambda:.0000023,'api-gateway':.000001,dynamodb:.00000075,s3:.023,cloudfront:.000001,cognito:.0055,cloudwatch:.5,waf:.0000006,sqs:.0000004,eventbridge:.000001,ses:.0001,'ecs-fargate':.04,eks:73,ec2:.04,rds:.05,aurora:.07,elasticache:.035,sns:.0000005,'step-functions':.000025,kinesis:.015,opensearch:.08,glue:.44,athena:5,redshift:.25,quicksight:.3,sagemaker:.1,bedrock:.003,'iot-core':.000001,route53:.5,acm:0,kms:1,'secrets-manager':.4,xray:.000005,appsync:.000004,efs:.03,shield:0,'iam-identity-center':0},region_multipliers:{'us-east-1':1,'us-east-2':1,'us-west-2':1.04,'eu-west-1':1.08,'eu-west-2':1.1,'eu-west-3':1.12,'eu-central-1':1.1,'eu-central-2':1.15,'eu-south-1':1.12,'eu-south-2':1.14,'eu-north-1':1.06,'ap-southeast-1':1.16,'ap-southeast-2':1.18,'ap-northeast-1':1.15}});

export function emptyVault(){return {schema_version:2,state_revision:0,created_at:new Date().toISOString(),updated_at:new Date().toISOString(),tenant:null,memberships:[],projects:[],analyses:{},audit:[],accountEstimates:{},accountEstimateRevisions:{},actualCosts:{},actualCostRevisions:{},privacyRequests:[],pricingCatalog:defaultPricing(),awsDiscovery:null};}
function normalize(v){const base=emptyVault(),x=(v&&typeof v==='object')?v:{};const pricing=x.pricingCatalog&&typeof x.pricingCatalog==='object'?x.pricingCatalog:base.pricingCatalog;return {...base,...x,schema_version:2,state_revision:Number.isInteger(Number(x.state_revision))?Number(x.state_revision):0,created_at:x.created_at||base.created_at,updated_at:x.updated_at||base.updated_at,memberships:Array.isArray(x.memberships)?x.memberships:[],projects:Array.isArray(x.projects)?x.projects:[],analyses:x.analyses&&typeof x.analyses==='object'?x.analyses:{},audit:Array.isArray(x.audit)?x.audit:[],accountEstimates:x.accountEstimates&&typeof x.accountEstimates==='object'?x.accountEstimates:{},accountEstimateRevisions:x.accountEstimateRevisions&&typeof x.accountEstimateRevisions==='object'?x.accountEstimateRevisions:{},actualCosts:x.actualCosts&&typeof x.actualCosts==='object'?x.actualCosts:{},actualCostRevisions:x.actualCostRevisions&&typeof x.actualCostRevisions==='object'?x.actualCostRevisions:{},privacyRequests:Array.isArray(x.privacyRequests)?x.privacyRequests:[],awsDiscovery:x.awsDiscovery&&typeof x.awsDiscovery==='object'?x.awsDiscovery:null,pricingCatalog:(pricing&&pricing.rates&&typeof pricing.rates==='object')?{...base.pricingCatalog,...pricing,rates:{...(pricing.rates||{})},region_multipliers:{...(pricing.region_multipliers||{})}}:base.pricingCatalog};}
function safeJson(text,fallback){try{return JSON.parse(text)}catch{return fallback}}
function fallbackRead(){try{const direct=localStorage.getItem(FALLBACK_KEY);if(direct)return normalize(JSON.parse(direct));for(const key of LEGACY_KEYS){const raw=localStorage.getItem(key);if(raw)return normalize(JSON.parse(raw))}}catch{}return emptyVault()}
function fallbackWriteRaw(state){try{localStorage.setItem(FALLBACK_KEY,JSON.stringify(state))}catch(e){throw new Error(`Browser fallback storage could not save the vault (${e?.name||'storage error'}). Export a backup, free browser storage, or use a browser with IndexedDB enabled.`)}}
function fallbackHistory(){try{const x=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return []}}
function fallbackWriteHistory(rows){try{localStorage.setItem(HISTORY_KEY,JSON.stringify(rows.slice(-MAX_RECOVERY)))}catch{}}
function metaRead(){try{return safeJson(localStorage.getItem(META_KEY)||'{}',{})}catch{return {}}}
function metaWrite(patch){const value={...metaRead(),...patch};try{localStorage.setItem(META_KEY,JSON.stringify(value))}catch{}return value}
function canUseIndexedDB(){return typeof indexedDB!=='undefined'&&indexedDB&&typeof indexedDB.open==='function'}
function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE);if(!db.objectStoreNames.contains(RECOVERY_STORE))db.createObjectStore(RECOVERY_STORE,{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('IndexedDB open failed'))})}
async function idbGet(){const db=await openDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),req=tx.objectStore(STORE).get(STATE_KEY);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}finally{db.close()}}
async function idbPut(value){const db=await openDb();try{await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(value,STATE_KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('IndexedDB transaction aborted'))})}finally{db.close()}}
async function idbCompareAndPut(incoming,{force=false}={}){const db=await openDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite'),store=tx.objectStore(STORE),req=store.get(STATE_KEY);let current=null,value=null,conflict=null;req.onsuccess=()=>{current=normalize(req.result||emptyVault());if(!force&&incoming.state_revision!==current.state_revision){conflict=new Error(`Local vault changed in another tab (expected revision ${incoming.state_revision}, current ${current.state_revision}). Reload before saving.`);conflict.status=409;tx.abort();return}value=normalize({...incoming,state_revision:current.state_revision+1,updated_at:new Date().toISOString()});store.put(value,STATE_KEY)};req.onerror=()=>reject(req.error);tx.oncomplete=()=>resolve({current,value});tx.onabort=()=>reject(conflict||tx.error||new Error('IndexedDB transaction aborted'));tx.onerror=()=>{}})}finally{db.close()}}
async function idbDelete(){const db=await openDb();try{await new Promise((resolve,reject)=>{const tx=db.transaction([STORE,RECOVERY_STORE],'readwrite');tx.objectStore(STORE).delete(STATE_KEY);tx.objectStore(RECOVERY_STORE).clear();tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}finally{db.close()}}
async function idbRecoveryPut(row){const db=await openDb();try{await new Promise((resolve,reject)=>{const tx=db.transaction(RECOVERY_STORE,'readwrite');tx.objectStore(RECOVERY_STORE).put(row);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}finally{db.close()}}
async function idbRecoveryList(){const db=await openDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(RECOVERY_STORE,'readonly'),req=tx.objectStore(RECOVERY_STORE).getAll();req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error)})}finally{db.close()}}
async function idbRecoveryDelete(id){const db=await openDb();try{await new Promise((resolve,reject)=>{const tx=db.transaction(RECOVERY_STORE,'readwrite');tx.objectStore(RECOVERY_STORE).delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}finally{db.close()}}
async function rawRead(){if(canUseIndexedDB()){try{return await idbGet()}catch{}}return fallbackRead()}
async function rawWrite(value){if(canUseIndexedDB()){try{await idbPut(value);return}catch{}}fallbackWriteRaw(value)}
function serialized(fn){const next=localQueue.then(fn,fn);localQueue=next.catch(()=>{});return next}
async function withLock(fn){if(typeof navigator!=='undefined'&&navigator.locks?.request)return navigator.locks.request('awsfc-local-vault',{mode:'exclusive'},fn);return serialized(fn)}
async function sha256(text){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function b64(bytes){let text='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)text+=String.fromCharCode(...bytes.subarray(i,i+chunk));return btoa(text)}
function unb64(text){return Uint8Array.from(atob(text),c=>c.charCodeAt(0))}
async function addRecovery(current){if(!current||!current.tenant&&!current.projects?.length)return;const snapshotText=JSON.stringify(current),snapshotBytes=new TextEncoder().encode(snapshotText).byteLength;if(snapshotBytes>MAX_RECOVERY_SNAPSHOT_BYTES){metaWrite({last_recovery_skip_at:new Date().toISOString(),last_recovery_skip_reason:'snapshot_too_large'});return;}const row={id:`rev-${current.state_revision}-${Date.now()}`,created_at:new Date().toISOString(),state_revision:current.state_revision,project_count:current.projects?.length||0,state:current};if(canUseIndexedDB()){try{await idbRecoveryPut(row);let rows=(await idbRecoveryList()).sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at)));while(rows.length>MAX_RECOVERY){const old=rows.shift();await idbRecoveryDelete(old.id)};return}catch{}}
const rows=fallbackHistory();rows.push(row);fallbackWriteHistory(rows);}

export async function loadVault(){const state=await rawRead();if(!state){const empty=emptyVault();await rawWrite(empty);return empty}const normalized=normalize(state);if(normalized.schema_version!==state.schema_version){await rawWrite(normalized)}return normalized}
export async function saveVault(state,{force=false,checkpoint=true}={}){return withLock(async()=>{const incoming=normalize(state);if(canUseIndexedDB()){try{const {current,value}=await idbCompareAndPut(incoming,{force});if(checkpoint)await addRecovery(current);return value}catch(e){if(e?.status===409)throw e;/* IndexedDB may be blocked despite exposing the API; preserve the documented fallback. */}}const current=normalize(fallbackRead()||emptyVault());if(!force&&incoming.state_revision!==current.state_revision){const err=new Error(`Local vault changed in another tab (expected revision ${incoming.state_revision}, current ${current.state_revision}). Reload before saving.`);err.status=409;throw err}if(checkpoint)await addRecovery(current);const value=normalize({...incoming,state_revision:current.state_revision+1,updated_at:new Date().toISOString()});fallbackWriteRaw(value);return value})}
export async function resetVault(){return withLock(async()=>{if(canUseIndexedDB()){try{await idbDelete()}catch{}}try{localStorage.removeItem(FALLBACK_KEY);for(const key of LEGACY_KEYS)localStorage.removeItem(key);localStorage.removeItem(HISTORY_KEY)}catch{}return emptyVault()})}

async function makeEnvelope({mark=true}={}){const state=await loadVault(),payload=JSON.stringify(state),checksum=await sha256(payload),envelope={format:'awsfc-local-backup',format_version:2,exported_at:new Date().toISOString(),application:'AWS Friendly Counsellor',web_milestone:'M5-A1',payload_sha256:checksum,state};if(mark)metaWrite({last_backup_at:envelope.exported_at,last_backup_kind:'plain',last_backup_revision:state.state_revision});return envelope}
export async function exportVault(){return makeEnvelope({mark:true})}
export async function importVault(payload){const data=typeof payload==='string'?JSON.parse(payload):payload;if(!data||typeof data!=='object')throw new Error('Backup is not a JSON object.');let state=data.format==='awsfc-local-backup'?data.state:data;if(!state||typeof state!=='object')throw new Error('Backup does not contain application state.');if(data.format==='awsfc-local-backup'&&data.format_version>=2){const actual=await sha256(JSON.stringify(state));if(!data.payload_sha256||actual!==data.payload_sha256)throw new Error('Backup integrity check failed (SHA-256 mismatch).')}const imported=normalize(state);return withLock(async()=>{const current=normalize(await rawRead()||emptyVault());await addRecovery(current);const value=normalize({...imported,state_revision:current.state_revision+1,updated_at:new Date().toISOString()});await rawWrite(value);metaWrite({last_restore_at:new Date().toISOString(),last_restore_source:data.format||'legacy'});return value})}

async function deriveKey(passphrase,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(passphrase),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt,iterations:250000},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
export async function exportEncryptedVault(passphrase){if(String(passphrase||'').length<8)throw new Error('Use a passphrase of at least 8 characters.');const envelope=await makeEnvelope({mark:false}),plain=new TextEncoder().encode(JSON.stringify(envelope)),salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await deriveKey(passphrase,salt),cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain)),out={format:'awsfc-local-backup-encrypted',format_version:1,algorithm:'AES-GCM',kdf:'PBKDF2-SHA256',iterations:250000,created_at:new Date().toISOString(),salt:b64(salt),iv:b64(iv),ciphertext:b64(cipher)};metaWrite({last_backup_at:out.created_at,last_backup_kind:'encrypted',last_backup_revision:envelope.state.state_revision});return out}
export async function importEncryptedVault(payload,passphrase){const data=typeof payload==='string'?JSON.parse(payload):payload;if(data?.format!=='awsfc-local-backup-encrypted')return importVault(data);if(String(passphrase||'').length<8)throw new Error('Encrypted backup requires its passphrase.');try{const salt=unb64(data.salt),iv=unb64(data.iv),cipher=unb64(data.ciphertext),key=await deriveKey(passphrase,salt),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,cipher),decoded=new TextDecoder().decode(plain);return importVault(decoded)}catch(e){throw new Error('Encrypted backup could not be decrypted. Check the passphrase and file integrity.')}}

export async function recoveryList(){let rows=[];if(canUseIndexedDB()){try{rows=await idbRecoveryList()}catch{rows=fallbackHistory()}}else rows=fallbackHistory();return rows.sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).map(({state,...meta})=>meta)}
export async function recoveryRestore(id){let rows=[];if(canUseIndexedDB()){try{rows=await idbRecoveryList()}catch{rows=fallbackHistory()}}else rows=fallbackHistory();const row=rows.find(x=>x.id===id);if(!row)throw new Error('Recovery checkpoint not found.');return saveVault(normalize(row.state),{force:true,checkpoint:true})}
export function backupStatus(){const m=metaRead(),last=m.last_backup_at||null,age_days=last?Math.floor((Date.now()-new Date(last).getTime())/86400000):null;return {last_backup_at:last,last_backup_kind:m.last_backup_kind||null,last_backup_revision:m.last_backup_revision??null,last_restore_at:m.last_restore_at||null,age_days,recommended:age_days===null||age_days>=7,critical:age_days===null||age_days>=30}}
export async function requestPersistentStorage(){if(typeof navigator==='undefined'||!navigator.storage)return {supported:false,persisted:false};let persisted=false;try{persisted=await navigator.storage.persisted?.()||false;if(!persisted&&navigator.storage.persist)persisted=await navigator.storage.persist()}catch{}return {supported:true,persisted}}
export async function vaultInfo(){const backup=backupStatus();let persisted=null,estimate=null;if(typeof navigator!=='undefined'&&navigator.storage){try{persisted=await navigator.storage.persisted?.()??null}catch{}try{estimate=await navigator.storage.estimate?.()??null}catch{}}return {storage:canUseIndexedDB()?'IndexedDB':'localStorage fallback',database:canUseIndexedDB()?DB_NAME:FALLBACK_KEY,schema_version:2,network_required:false,persisted,usage_bytes:estimate?.usage??null,quota_bytes:estimate?.quota??null,backup}}
