import { esc, formatDate, num } from './utils.js';

const regions=['eu-central-1','eu-west-1','eu-west-2','eu-west-3','eu-north-1','eu-central-2','eu-south-1','eu-south-2','us-east-1','us-east-2','us-west-1','us-west-2','ap-southeast-1','ap-southeast-2','ap-northeast-1'];
const regionOptions=(sel='eu-central-1')=>regions.map(r=>`<option ${r===sel?'selected':''}>${r}</option>`).join('');
const budgetOptions=(sel='medium')=>['low','medium','high'].map(x=>`<option value="${x}" ${x===sel?'selected':''}>${x[0].toUpperCase()+x.slice(1)}</option>`).join('');
const pill=(v,k=v)=>`<span class="pill ${esc(k)}">${esc(v)}</span>`;

export function landing(settings){
  return `<main class="landing"><div class="landing-grid"><section class="hero">
  <div class="brand big"><span class="logo">☁</span><span>AWS Friendly Counsellor</span></div>
  <h1>Design AWS with confidence,<br><span>without starting as a cloud architect.</span></h1>
  <p class="lead">Guided architecture, cost ranges, service rationale, implementation steps, immutable project history, audit and Terraform baselines — in one web application.</p>
  <div class="hero-actions">${settings.authMode==='cognito'?'<button class="btn primary" data-action="login">Sign in with Cognito</button>':'<a class="btn primary" href="#/dashboard">Open application</a>'}<a class="btn ghost" href="#/settings">Connection settings</a></div>
  <div class="trust-row"><span>✓ No secrets in GitHub Pages</span><span>✓ AWS backend remains authoritative</span><span>✓ Demo works offline</span></div>
  </section><aside class="hero-card"><div class="terminal-head"><span></span><span></span><span></span></div><div class="mock-card">
  <div class="eyebrow">Architecture result</div><h3>Serverless customer portal</h3>
  <div class="flow"><span>CloudFront</span><b>→</b><span>API Gateway</span><b>→</b><span>Lambda</span><b>→</b><span>DynamoDB</span></div>
  <div class="metric-grid"><div><strong>$84–$214</strong><small>monthly range</small></div><div><strong>8</strong><small>AWS services</small></div><div><strong>High</strong><small>resilience target</small></div></div>
  <div class="status good">Security baseline included</div></div></aside></div></main>`;
}

export function shell({route,settings,identity,body,health}){
  const nav=[['/dashboard','⌂','Dashboard'],['/advisor','✦','Friendly Advisor'],['/projects','▦','Projects'],['/team','♟','Team'],['/audit','≡','Audit'],['/settings','⚙','Settings']];
  const links=nav.map(([p,i,l])=>`<a href="#${p}" class="${route===p||route.startsWith(p+'/')?'active':''}"><span>${i}</span>${l}</a>`).join('');
  return `<div class="app-shell"><aside class="sidebar"><a class="brand" href="#/dashboard"><span class="logo">☁</span><span>AWS Friendly<br><strong>Counsellor</strong></span></a><nav>${links}</nav><div class="side-bottom"><div class="mode-card"><span class="dot ${esc(settings.authMode)}"></span><div><strong>${esc(settings.authMode.toUpperCase())}</strong><small>${settings.authMode==='demo'?'Browser simulation':esc(settings.apiBaseUrl||'API not configured')}</small></div></div><a href="#/about" class="tiny-link">Release & limits</a></div></aside><section class="workspace"><header class="topbar"><button class="mobile-menu" data-action="toggle-menu" aria-label="Menu">☰</button><div><strong>${identity?.username?esc(identity.username):'AWS Friendly Counsellor'}</strong><small>${identity?.subject?esc(identity.subject):'Not connected'}</small></div><div class="top-actions"><span class="health ${health?.status==='healthy'?'ok':'warn'}">${health?.status==='healthy'?'● Ready':'● Check backend'}</span>${settings.authMode==='cognito'?'<button class="btn mini ghost" data-action="logout">Sign out</button>':''}</div></header><main class="content">${body}</main></section></div>`;
}

export function onboarding(settings){
  return `<section class="page narrow"><div class="eyebrow">First run</div><h1>Connect a workspace</h1><p class="muted">Projects are tenant-scoped. Create a workspace or connect an existing tenant ID.</p><div class="two-col"><form class="panel" id="create-tenant-form"><h2>Create workspace</h2><label>Workspace name<input name="name" required minlength="2" maxlength="120" placeholder="Acme Cloud Team"></label><label>Slug <small>optional</small><input name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="acme-cloud-team"></label><button class="btn primary" type="submit">Create workspace</button></form><form class="panel" id="connect-tenant-form"><h2>Existing workspace</h2><label>Tenant ID<input name="tenantId" required placeholder="tenant_…"></label><button class="btn" type="submit">Connect</button><p class="hint">The server validates membership; knowing a tenant ID never grants access.</p></form></div><p class="hint">Mode: <strong>${esc(settings.authMode)}</strong>. ${settings.authMode==='demo'?'This creates browser-local demo data.':'Your API must be reachable and CORS must allow this site origin.'}</p></section>`;
}

const projectRow=p=>`<a class="project-row" href="#/project/${encodeURIComponent(p.id)}"><div><strong>${esc(p.name)}</strong><small>${esc(p.region)} · ${num(p.estimated_users)} users</small></div>${pill(p.status,p.status)}</a>`;

export function dashboard({tenant,projects=[],projectsHasMore=false,health,identity,latest}){
  return `<section class="page"><div class="page-head"><div><div class="eyebrow">${tenant?esc(tenant.name):'Workspace'}</div><h1>Good to see you${identity?.username?', '+esc(identity.username.split(' ')[0]):''}.</h1><p class="muted">Turn a plain-language workload into a documented AWS baseline.</p></div><a class="btn primary" href="#/advisor">✦ Start guided analysis</a></div>
  <div class="stat-grid"><div class="stat"><small>Projects loaded</small><strong>${projects.length}${projectsHasMore?'+':''}</strong><span>${projects.filter(p=>p.status==='active').length} active in this page</span></div><div class="stat"><small>Backend</small><strong>${health?.status==='healthy'?'Ready':'Unknown'}</strong><span>${esc(health?.environment||'not checked')}</span></div><div class="stat"><small>Persistence</small><strong>${esc(health?.persistence_backend||'—')}</strong><span>${esc(health?.persistence_status||'')}</span></div><div class="stat"><small>Recent analysis sample</small><strong>${esc(latest?.typical_monthly_cost||'—')}</strong><span>${latest?`v${latest.version} · ${formatDate(latest.created_at)}`:'No history in visible projects'}</span></div></div>
  <div class="dash-grid"><section class="panel"><div class="panel-head"><h2>Projects</h2><a href="#/projects">View all</a></div>${projects.length?`<div class="project-list">${projects.slice(0,5).map(projectRow).join('')}</div>`:'<div class="empty"><div class="empty-icon">▦</div><h3>No projects yet</h3><p>Create one or use the Friendly Advisor first.</p><a class="btn" href="#/projects">Create project</a></div>'}</section><section class="panel"><h2>How the counsellor works</h2><ol class="steps"><li><span>1</span><div><strong>Describe the workload</strong><small>Business language is enough.</small></div></li><li><span>2</span><div><strong>Review the baseline</strong><small>Services, costs, reasoning and assumptions.</small></div></li><li><span>3</span><div><strong>Persist the project</strong><small>Immutable analysis history and audit.</small></div></li><li><span>4</span><div><strong>Generate infrastructure</strong><small>Terraform baseline with explicit caveats.</small></div></li></ol></section></div></section>`;
}

export function advisor(initial={}){
  return `<section class="page"><div class="page-head"><div><div class="eyebrow">Guided planning</div><h1>Friendly Advisor</h1><p class="muted">Describe the workload in ordinary language. The planner stays deterministic and versioned.</p></div>${pill('Contract 1.3.0','info')}</div><form id="advisor-form" class="wizard panel"><div class="wizard-step"><span>1</span><div><h3>What are you building?</h3><label>Product, data and important behaviors<textarea name="description" minlength="10" maxlength="5000" required placeholder="A customer portal with login, file uploads, analytics, webhooks and background reports…">${esc(initial.description||'')}</textarea></label><div class="chips"><button type="button" data-template="SaaS">SaaS</button><button type="button" data-template="E-commerce">E-commerce</button><button type="button" data-template="API">API</button><button type="button" data-template="Data">Data platform</button><button type="button" data-template="ML">ML inference</button></div></div></div><div class="wizard-step"><span>2</span><div><h3>Scale & constraints</h3><div class="form-grid"><label>Monthly active users<input type="number" name="estimated_users" min="1" max="100000000" value="${initial.estimated_users||5000}" required></label><label>Budget profile<select name="budget">${budgetOptions(initial.budget||'medium')}</select></label><label>AWS region<select name="region">${regionOptions(initial.region||'eu-central-1')}</select></label><label class="check"><input type="checkbox" name="advanced_guide" ${initial.advanced_guide===false?'':'checked'}><span>Include advanced operations guide</span></label></div></div></div><div class="wizard-actions"><button class="btn primary large" type="submit">Analyze architecture →</button><span class="hint">Transparent deterministic recommendations, not a probabilistic cost forecast.</span></div></form><div id="advisor-result"></div></section>`;
}

export function analysisResult(result,{showPersist=true}={}){
  if(!result)return '';
  const a=result.analysis,c=result.cost_analysis,g=result.implementation_guide;
  const services=(result.services||[]).map(s=>`<article class="service"><div class="service-icon">AWS</div><div><strong>${esc(s.name)}</strong><small>${esc(s.category)}</small><p>${esc(s.why_needed)}</p></div><span class="price">${esc(s.typical_monthly)}</span></article>`).join('');
  const phases=(g?.phases||[]).map((p,i)=>`<article><span>${i+1}</span><h3>${esc(p.name)}</h3><small>${esc(p.duration)}</small><ul>${(p.steps||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article>`).join('');
  return `<section class="result-stack"><div class="result-hero panel"><div><div class="eyebrow">Recommended baseline</div><h2>${esc(a.project_type)}</h2><p>Confidence <strong>${Math.round(a.confidence*100)}%</strong> · ${(a.detected_features||[]).length} detected features</p></div><div class="cost-badge"><small>Typical monthly</small><strong>${esc(c.summary.typical)}</strong><span>${esc(c.summary.minimum)} – ${esc(c.summary.maximum)}</span></div></div><div class="result-grid"><section class="panel"><h2>Recommended services</h2><div class="service-list">${services}</div></section><section class="panel"><h2>Cost envelope</h2><div class="cost-three"><div><small>Minimum</small><strong>${esc(c.summary.minimum)}</strong></div><div><small>Typical</small><strong>${esc(c.summary.typical)}</strong></div><div><small>Maximum</small><strong>${esc(c.summary.maximum)}</strong></div></div><ul class="compact">${(c.assumptions||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section></div><section class="panel"><div class="panel-head"><div><div class="eyebrow">Implementation</div><h2>${esc(g?.introduction?.title||'Implementation guide')}</h2></div><span>${esc(g?.introduction?.estimated_effort||'')}</span></div><p class="muted">${esc(g?.introduction?.overview||'')}</p><div class="phase-grid">${phases}</div></section><div class="action-strip">${showPersist?'<button class="btn primary" data-action="save-analysis-project">Save as project</button>':''}<button class="btn" data-action="generate-iac">Generate Terraform</button><button class="btn" data-action="generate-report">Generate report</button><button class="btn ghost" data-action="print">Print</button></div><div id="generated-output"></div></section>`;
}

export function projectsPage(projects=[],nextCursor=null){
  return `<section class="page"><div class="page-head"><div><div class="eyebrow">Durable workspace</div><h1>Projects</h1><p class="muted">Versioned specifications with immutable analysis history.</p></div><button class="btn primary" data-action="show-project-form">+ New project</button></div><div id="project-create-slot"></div><section class="panel">${projects.length?`<div class="project-table"><div class="thead"><span>Project</span><span>Region</span><span>Users</span><span>Status</span><span>Revision</span></div>${projects.map(p=>`<a href="#/project/${encodeURIComponent(p.id)}"><span><strong>${esc(p.name)}</strong><small>${esc(p.description).slice(0,90)}</small></span><span>${esc(p.region)}</span><span>${num(p.estimated_users)}</span><span>${pill(p.status,p.status)}</span><span>r${p.revision}</span></a>`).join('')}</div>`:'<div class="empty"><h3>No projects in this tenant</h3><p>Create your first durable project.</p></div>'}${nextCursor?`<div class="form-actions"><a class="btn" href="#/projects?cursor=${encodeURIComponent(nextCursor)}">Next page →</a></div>`:''}</section></section>`;
}

export function projectCreateForm(initial={}){
  return `<form id="project-create-form" class="panel inline-form"><div class="panel-head"><h2>New project</h2><button type="button" class="icon-btn" data-action="hide-project-form">×</button></div><div class="form-grid"><label>Project name<input name="name" required minlength="2" maxlength="120" value="${esc(initial.name||'')}"></label><label>Status<select name="status"><option>draft</option><option>active</option></select></label><label class="span2">Description<textarea name="description" required minlength="10" maxlength="5000">${esc(initial.description||'')}</textarea></label><label>Monthly active users<input name="estimated_users" type="number" min="1" max="100000000" value="${initial.estimated_users||5000}"></label><label>Budget<select name="budget">${budgetOptions(initial.budget||'medium')}</select></label><label>Region<select name="region">${regionOptions(initial.region||'eu-central-1')}</select></label></div><button class="btn primary" type="submit">Create project</button></form>`;
}

export function projectDetail(p,analyses=[],nextCursor=null){
  const history=analyses.length?`<div class="history">${analyses.map(a=>`<button data-action="open-analysis" data-version="${a.version}"><span>v${a.version}</span><div><strong>${esc(a.project_type)}</strong><small>${formatDate(a.created_at)}</small></div><b>${esc(a.typical_monthly_cost)}</b></button>`).join('')}</div>`:'<div class="empty small"><p>No persisted analyses yet.</p></div>';
  return `<section class="page"><div class="page-head"><div><a class="back" href="#/projects">← Projects</a><div class="eyebrow">${esc(p.id)}</div><h1>${esc(p.name)}</h1><p class="muted">Revision ${p.revision} · updated ${formatDate(p.updated_at)}</p></div>${pill(p.status,p.status)}</div><div class="detail-grid"><section class="panel"><h2>Project specification</h2><form id="project-edit-form"><input type="hidden" name="expected_revision" value="${p.revision}"><label>Name<input name="name" required minlength="2" maxlength="120" value="${esc(p.name)}"></label><label>Description<textarea name="description" required minlength="10" maxlength="5000">${esc(p.description)}</textarea></label><div class="form-grid"><label>Users<input type="number" name="estimated_users" min="1" max="100000000" value="${p.estimated_users}"></label><label>Budget<select name="budget">${budgetOptions(p.budget)}</select></label><label>Region<select name="region">${regionOptions(p.region)}</select></label><label>Status<select name="status">${['draft','active','archived'].map(x=>`<option ${x===p.status?'selected':''}>${x}</option>`).join('')}</select></label></div><button class="btn" type="submit">Save changes</button></form></section><section class="panel"><h2>Analysis actions</h2><p class="muted">Each persisted run is immutable and receives the next sequential version.</p><button class="btn primary block" data-action="run-project-analysis" ${p.status==='archived'?'disabled':''}>✦ Run & persist new analysis</button><button class="btn block" data-action="project-iac">Generate Terraform</button><button class="btn block" data-action="project-report">Generate report</button>${p.status==='archived'?'<p class="warning">Archived projects cannot receive new analysis versions.</p>':''}<div id="project-output"></div></section></div><section class="panel"><div class="panel-head"><h2>Immutable analysis history</h2><span>${analyses.length} shown</span></div>${history}${nextCursor?`<div class="form-actions"><a class="btn" href="#/project/${encodeURIComponent(p.id)}?analysis_cursor=${encodeURIComponent(nextCursor)}">Next history page →</a></div>`:''}</section><div id="analysis-version-slot"></div></section>`;
}

export function teamPage(members=[],nextCursor=null){
  const rows=members.length?`<div class="members">${members.map(m=>`<article><div class="avatar">${esc(m.subject.slice(0,2).toUpperCase())}</div><div><strong>${esc(m.subject)}</strong><small>${esc(m.status)} · revision ${m.revision}</small></div>${pill(m.role,'info')}${m.role!=='owner'?`<button class="icon-btn" data-action="edit-member" data-subject="${esc(m.subject)}" data-role="${esc(m.role)}" data-status="${esc(m.status)}" data-revision="${m.revision}">✎</button>`:''}</article>`).join('')}</div>`:'<p class="muted">No memberships returned.</p>';
  return `<section class="page"><div class="page-head"><div><div class="eyebrow">Tenant administration</div><h1>Team</h1><p class="muted">Viewer, editor and admin memberships. Owner transfer is intentionally not exposed by the generic API.</p></div></div><div class="two-col"><section class="panel"><h2>Members</h2>${rows}</section><form class="panel" id="member-create-form"><h2>Add member</h2><label>Cognito subject<input name="subject" required maxlength="256" placeholder="user subject / UUID"></label><label>Role<select name="role"><option>viewer</option><option>editor</option><option>admin</option></select></label><button class="btn primary" type="submit">Grant membership</button><p class="hint">The backend applies role ceilings and tenant authorization.</p></form></div>${nextCursor?`<div class="form-actions"><a class="btn" href="#/team?cursor=${encodeURIComponent(nextCursor)}">Next member page →</a></div>`:''}<div id="member-edit-slot"></div></section>`;
}

export function memberEditForm(m){
  return `<form class="panel inline-form" id="member-edit-form"><h2>Edit ${esc(m.subject)}</h2><input type="hidden" name="subject" value="${esc(m.subject)}"><input type="hidden" name="expected_revision" value="${m.revision}"><div class="form-grid"><label>Role<select name="role">${['viewer','editor','admin'].map(x=>`<option ${x===m.role?'selected':''}>${x}</option>`).join('')}</select></label><label>Status<select name="status"><option ${m.status==='active'?'selected':''}>active</option><option ${m.status==='suspended'?'selected':''}>suspended</option></select></label></div><button class="btn" type="submit">Apply change</button></form>`;
}

export function auditPage(events=[],nextCursor=null){
  const rows=events.length?`<div class="audit-list">${events.map(e=>`<article><span class="audit-dot"></span><div><strong>${esc(e.action)}</strong><small>${esc(e.resource_type)} · ${esc(e.resource_id)}</small><p>${formatDate(e.occurred_at)} · actor ${esc(e.actor_subject)}</p></div><code>${esc(e.request_id)}</code></article>`).join('')}</div>`:'<div class="empty"><p>No audit events returned.</p></div>';
  return `<section class="page"><div class="page-head"><div><div class="eyebrow">Governance</div><h1>Audit trail</h1><p class="muted">Actor, action, resource and request ID for critical tenant mutations.</p></div></div><section class="panel">${rows}${nextCursor?`<div class="form-actions"><a class="btn" href="#/audit?cursor=${encodeURIComponent(nextCursor)}">Next audit page →</a></div>`:''}</section></section>`;
}

export function settingsPage(s){
  return `<section class="page narrow"><div class="eyebrow">Runtime connection</div><h1>Settings</h1><p class="muted">GitHub Pages contains no AWS secret. Choose demo, local development, or Cognito-backed AWS mode.</p><form id="settings-form" class="panel settings-form"><label>Authentication mode<select name="authMode"><option value="demo" ${s.authMode==='demo'?'selected':''}>Demo — browser-local simulation</option><option value="cognito" ${s.authMode==='cognito'?'selected':''}>Cognito — production/staging</option><option value="local" ${s.authMode==='local'?'selected':''}>Local debug — local/test backend only</option></select></label><label>API base URL<input name="apiBaseUrl" type="url" placeholder="https://abc.execute-api.eu-central-1.amazonaws.com/staging" value="${esc(s.apiBaseUrl)}"></label><div class="settings-group"><h3>Cognito / PKCE</h3><label>Cognito domain<input name="cognitoDomain" type="url" placeholder="https://your-domain.auth.eu-central-1.amazoncognito.com" value="${esc(s.cognitoDomain)}"></label><label>Public app client ID<input name="cognitoClientId" value="${esc(s.cognitoClientId)}"></label><label>Scopes<input name="cognitoScopes" value="${esc(s.cognitoScopes)}"></label><label>Redirect URI<input name="redirectUri" value="${esc(s.redirectUri)}"></label><label>Logout URI<input name="logoutUri" value="${esc(s.logoutUri)}"></label></div><div class="settings-group"><h3>Workspace</h3><label>Tenant ID<input name="tenantId" value="${esc(s.tenantId)}" placeholder="tenant_…"></label></div><div class="settings-group"><h3>Local debug identity</h3><label>Subject<input name="localSubject" value="${esc(s.localSubject)}"></label><label>Username<input name="localUsername" value="${esc(s.localUsername)}"></label></div><div class="form-actions"><button class="btn primary" type="submit">Save settings</button><button class="btn ghost" type="button" data-action="test-connection">Test connection</button><button class="btn danger ghost" type="button" data-action="reset-settings">Reset</button></div></form><section class="security-note"><strong>Security boundary</strong><p>Cognito uses Authorization Code + PKCE. Tokens are kept in sessionStorage, never in the repository. AWS account credentials and client secrets must never be placed in this frontend.</p></section></section>`;
}

export function aboutPage(s){
  return `<section class="page narrow"><div class="eyebrow">Release information</div><h1>AWS Friendly Counsellor Web</h1><section class="panel"><dl class="facts"><div><dt>Web milestone</dt><dd>${esc(s.webVersion)}</dd></div><div><dt>Backend baseline</dt><dd>3.6.3-m1.5.3 local RC</dd></div><div><dt>API contract</dt><dd>1.3.0</dd></div><div><dt>Hosting target</dt><dd>GitHub Pages / any static host</dd></div></dl><h2>What this release preserves</h2><p>Guided analysis, tenant/project CRUD, immutable analyses, RBAC administration, audit, cost breakdown, implementation guidance, narrative reports and Terraform generation remain reachable from the web interface.</p><h2>What remains an AWS gate</h2><p>The UI does not convert local evidence into cloud evidence. Cognito, API Gateway, DynamoDB, WAF, CloudWatch, CloudTrail, canary rollback and PITR remain subject to the M1.5 live staging acceptance record.</p></section></section>`;
}

export function errorCard(title,message){return `<div class="panel error-card"><strong>${esc(title)}</strong><p>${esc(message)}</p></div>`;}
