const mem=new Map();globalThis.localStorage={getItem:k=>mem.has(k)?mem.get(k):null,setItem:(k,v)=>mem.set(k,String(v)),removeItem:k=>mem.delete(k)};
if(!globalThis.crypto)globalThis.crypto=(await import('node:crypto')).webcrypto;
if(!globalThis.btoa)globalThis.btoa=s=>Buffer.from(s,'binary').toString('base64');
if(!globalThis.atob)globalThis.atob=s=>Buffer.from(s,'base64').toString('binary');
const {demoApi}=await import('../js/demo.js');
const assert=(ok,msg)=>{if(!ok)throw new Error(msg)};
const health=await demoApi.health();assert(health.status==='healthy','health');
const tenant=(await demoApi.createTenant({name:'Smoke Team'})).tenant;assert(tenant.id,'tenant');
const me=await demoApi.me();assert(me.subject==='demo-owner','identity');
const p=(await demoApi.createProject({name:'Portal',description:'A customer portal with login, uploads, background jobs and analytics dashboard.',estimated_users:12000,budget:'medium',region:'eu-central-1',status:'active'})).project;assert(p.revision===1,'project');
const a=(await demoApi.createProjectAnalysis(p.id,{advanced_guide:true})).analysis_version;assert(a.version===1,'analysis version');assert(a.result.services.length>=7,'services');
const list=await demoApi.listProjectAnalyses(p.id);assert(list.analysis_versions.length===1,'analysis list');
const iac=await demoApi.iac(a.request);assert(iac.terraform.files['main.tf'].includes('software_token_mfa_configuration'),'terraform MFA');
const report=await demoApi.narrative(a.request);assert(report.narrative_html.includes('Recommended services'),'report');
const members=await demoApi.listMemberships(tenant.id);assert(members.memberships[0].role==='owner','owner');
const audit=await demoApi.listAudit(tenant.id);assert(audit.audit_events.length>=3,'audit');
for(let i=0;i<54;i++) await demoApi.createProject({name:`Extra ${i}`,description:'Additional workload used to prove browser demo pagination behavior.',estimated_users:100+i,budget:'low',region:'eu-central-1',status:'draft'});
const page1=await demoApi.listProjects({limit:50});assert(page1.projects.length===50&&page1.next_cursor,'pagination first page');
const page2=await demoApi.listProjects({limit:50,cursor:page1.next_cursor});assert(page2.projects.length===5&&!page2.next_cursor,'pagination second page');
console.log('DEMO SMOKE PASS',JSON.stringify({tenant:tenant.id,project:p.id,analysis:a.version,services:a.result.services.length,audit:audit.audit_events.length,first:page1.projects.length,second:page2.projects.length}));
