const mem=new Map();
globalThis.localStorage={getItem:k=>mem.has(k)?mem.get(k):null,setItem:(k,v)=>mem.set(k,String(v)),removeItem:k=>mem.delete(k)};
if(!globalThis.crypto)globalThis.crypto=(await import('node:crypto')).webcrypto;
if(!globalThis.btoa)globalThis.btoa=s=>Buffer.from(s,'binary').toString('base64');
if(!globalThis.atob)globalThis.atob=s=>Buffer.from(s,'base64').toString('binary');
const {standaloneApi}=await import('../js/standalone.js');
const assert=(ok,msg)=>{if(!ok)throw new Error(msg)};

await standaloneApi.resetLocalData();
const h=await standaloneApi.health();
assert(h.status==='healthy'&&h.environment==='standalone'&&h.network_required===false,'standalone health');
const tenant=(await standaloneApi.createTenant({name:'Standalone Team'})).tenant;
assert(tenant.id,'tenant');
const me=await standaloneApi.me();assert(me.subject==='local-owner','local identity');
const p=(await standaloneApi.createProject({name:'Offline SaaS',description:'A SaaS with login, uploads, background jobs, analytics and email notifications.',estimated_users:25000,budget:'medium',region:'eu-central-1',status:'active'})).project;
const av=(await standaloneApi.createProjectAnalysis(p.id,{advanced_guide:true})).analysis_version;
assert(av.version===1&&av.result.scenarios.length===3&&av.result.architecture_decisions.length,'analysis/scenarios/ADR');
const price=await standaloneApi.pricingQuote({region:'eu-central-1',usage:av.result.usage_profile,service_ids:av.result.services.map(x=>x.id),transfer_paths:[]});
assert(price.total_monthly>=0&&price.source_state==='embedded_snapshot','embedded pricing');
const custom=await standaloneApi.importPricingCatalog({version:'test-local-catalog',currency:'USD',rates:{lambda:.00001,'api-gateway':.000002,dynamodb:.000001,s3:.03,cloudfront:.000002,cognito:.006,cloudwatch:.6,waf:.000001,sqs:.000001,eventbridge:.000002,ses:.0002},region_multipliers:{'eu-central-1':1.2}});assert(custom.catalog.version==='test-local-catalog','pricing catalog import');
const repriced=await standaloneApi.pricingQuote({region:'eu-central-1',usage:av.result.usage_profile,service_ids:av.result.services.map(x=>x.id),transfer_paths:[]});assert(repriced.total_monthly!==price.total_monthly,'imported pricing affects quote');
const est=(await standaloneApi.createAccountEstimate(p.id,1,{account_id:'000000000000',rate_type:'AFTER_DISCOUNTS',ttl_days:30})).estimate;
assert(est.provider==='local_rate_profile'&&est.aws_estimate_id===null,'local equivalent estimate');
const actual=(await standaloneApi.createActualCost(p.id,{estimate_id:est.estimate_id,account_id:'000000000000',start_date:'2026-09-01',end_date:'2026-10-01',metric:'UnblendedCost',actual_total:price.total_monthly*0.95})).snapshot;
assert(actual.source==='local_manual'&&actual.api_request_count===0,'manual actual');
const cur=(await standaloneApi.importCur2(p.id,{estimate_id:est.estimate_id,account_id:'000000000000',start_date:'2026-09-01',end_date:'2026-10-01',rows:[{date:'2026-09-01',service:'AWS Lambda',amount:12.5,currency:'USD',estimated:false},{date:'2026-09-02',service:'Amazon S3',amount:3.5,currency:'USD',estimated:false}]})).snapshot;
assert(cur.source==='cur_2_0_import'&&cur.actual_total===16,'CUR import');
const bundle=await standaloneApi.getReportBundle(p.id,1);assert(bundle.files['PROVENANCE.json']&&bundle.workspace_sha256.length===64,'report bundle');
const game=await standaloneApi.gamification(tenant.id);assert(game.leaderboard.length===1,'gamification');
const privacy=await standaloneApi.privacyExport();assert(privacy.subject==='local-owner','privacy export');
const backup=await standaloneApi.backupExport();assert(backup.format==='awsfc-local-backup'&&backup.state.projects.length===1,'backup export');
await standaloneApi.resetLocalData();
let projects=await standaloneApi.listProjects({limit:10});assert(projects.projects.length===0,'reset');
const restored=await standaloneApi.backupImport(JSON.stringify(backup));assert(restored.projects===1&&restored.tenant_id===tenant.id,'backup restore');
projects=await standaloneApi.listProjects({limit:10});assert(projects.projects[0].name==='Offline SaaS','restored project');
console.log('STANDALONE SMOKE PASS',JSON.stringify({storage:h.persistence_backend,project:p.id,scenario_count:av.result.scenarios.length,price:price.total_monthly,actual:actual.actual_total,cur:cur.actual_total,backup_projects:backup.state.projects.length}));
